#!/bin/bash

if [ $# -ne 5 ]
then
  echo "Usage: $0 <group> <artifact> <version> <history> <target_ip>";
  exit 3;
fi

R_GROUP=$1
R_ARTIFACT=$2
R_VERSION=$3
R_HISTORY=$4
TARGET=$5

LOCAL_UNIQ_DIR=${R_GROUP}_${R_ARTIFACT}_${R_VERSION}_${R_HISTORY}_$$
mkdir $LOCAL_UNIQ_DIR

export CLASSPATH="radis-client/:radis-client/*"
java radis.client.Cli get $R_GROUP $R_ARTIFACT $R_VERSION $R_HISTORY $LOCAL_UNIQ_DIR

echo TODO process static files
cat $LOCAL_UNIQ_DIR/META-INF/revxxx.report
./deploy_from_disk $LOCAL_UNIQ_DIR $TARGET

