#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Usage: $0 <machine>"
	exit 3;
fi

MACHINE=$1

status=$(ssh web@$MACHINE "tail -n 20 ~/run/logs/catalina.out| grep \"INFO: Server startup in\" |tail -n 1|awk '{print \$(NF-1)}' ")
if [ $status ]&&[ $status -gt 10000 ]
then
	echo "yes"
else
	echo "no"
fi
