{
  'variables': {
   'UICPATH':'../uic',
  },
  'conditions': [
    ['OS=="linux"', {
      'target_defaults': {
        'cflags': [ '-g', '-O2', '-fpermissive', '-Wall'],
        'defines': ['OS_LINUX','BASE_DISABLE_POOL', 'LINUX64']
      },
    }]
  ],
  'targets': [
    {
      'target_name': 'uic',
      'type': 'static_library',
      'include_dirs': ['/opt/intel/include','/opt/intel/ipp/include',
                       '<(UICPATH)/core/uic/include', '<(UICPATH)/io/uic_io/include',
                       '<(UICPATH)/codec/image/jpeg/dec/include', '<(UICPATH)/codec/image/jpeg/common/include', '<(UICPATH)/codec/image/jpeg/enc/include',
                       '<(UICPATH)/codec/image/png/dec/include', '<(UICPATH)/codec/image/png/common/include', '<(UICPATH)/codec/image/png/enc/include',
                       '<(UICPATH)/codec/image/bmp/dec/include', '<(UICPATH)/codec/image/bmp/common/include', '<(UICPATH)/codec/image/bmp/enc/include'],
      'dependencies': [],
      'sources': [
          '<(UICPATH)/codec/image/jpeg/dec/src/bitstreamin.cpp',
          '<(UICPATH)/codec/image/jpeg/dec/src/dechtbl.cpp',
          '<(UICPATH)/codec/image/jpeg/dec/src/decqtbl.cpp',
          '<(UICPATH)/codec/image/jpeg/dec/src/jpegdec.cpp',
          '<(UICPATH)/codec/image/jpeg/dec/src/jpegdecrst.cpp',
          '<(UICPATH)/codec/image/jpeg/dec/src/uic_jpeg_dec.cpp',
          '<(UICPATH)/codec/image/jpeg/dec/include/bitstreamin.h',
          '<(UICPATH)/codec/image/jpeg/dec/include/dechtbl.h',
          '<(UICPATH)/codec/image/jpeg/dec/include/decqtbl.h',
          '<(UICPATH)/codec/image/jpeg/dec/include/jpegdec.h',
          '<(UICPATH)/codec/image/jpeg/dec/include/uic_jpeg_dec.h',
          '<(UICPATH)/codec/image/jpeg/enc/src/bitstreamout.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/enchtbl.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/encqtbl.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/jpegenc.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/jpegencrst.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/uic_jpeg_enc.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/bitstreamout.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/enchtbl.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/encqtbl.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/jpegenc.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/jpegencrst.cpp',
          '<(UICPATH)/codec/image/jpeg/enc/src/uic_jpeg_enc.cpp',
          '<(UICPATH)/codec/image/jpeg/common/include/colorcomp.h',
          '<(UICPATH)/codec/image/jpeg/common/include/colorcomp.h',
          '<(UICPATH)/codec/image/jpeg/common/include/jpegbase.h',
          '<(UICPATH)/codec/image/jpeg/common/include/jpegbase.h',
          '<(UICPATH)/codec/image/jpeg/common/include/metadata.h',
          '<(UICPATH)/codec/image/jpeg/common/include/metadata.h',
          '<(UICPATH)/codec/image/jpeg/common/include/precomp.h',
          '<(UICPATH)/codec/image/jpeg/common/include/precomp.h',
          '<(UICPATH)/codec/image/jpeg/common/src/colorcomp.cpp',
          '<(UICPATH)/codec/image/jpeg/common/src/jpegbase.cpp',
          '<(UICPATH)/codec/image/jpeg/common/src/metadata.cpp',
          '<(UICPATH)/codec/image/png/dec/src/uic_png_dec.cpp',
          '<(UICPATH)/codec/image/png/dec/include/uic_png_dec.h',
          '<(UICPATH)/codec/image/png/common/src/pngrtran.c',
          '<(UICPATH)/codec/image/png/common/src/pngwutil.c',
          '<(UICPATH)/codec/image/png/common/src/pngwio.c',
          '<(UICPATH)/codec/image/png/common/src/pngset.c',
          '<(UICPATH)/codec/image/png/common/src/pnggccrd.c',
          '<(UICPATH)/codec/image/png/common/src/example.c',
          '<(UICPATH)/codec/image/png/common/src/pngwrite.c',
          '<(UICPATH)/codec/image/png/common/src/pngget.c',
          '<(UICPATH)/codec/image/png/common/src/png.c',
          '<(UICPATH)/codec/image/png/common/src/pngtrans.c',
          '<(UICPATH)/codec/image/png/common/src/pngvcrd.c',
          '<(UICPATH)/codec/image/png/common/src/pngrutil.c',
          '<(UICPATH)/codec/image/png/common/src/pngpread.c',
          '<(UICPATH)/codec/image/png/common/src/pngwtran.c',
          '<(UICPATH)/codec/image/png/common/src/pngtest.c',
          '<(UICPATH)/codec/image/png/common/src/pngmem.c',
          '<(UICPATH)/codec/image/png/common/src/png.h',
          '<(UICPATH)/codec/image/png/common/src/pngrio.c',
          '<(UICPATH)/codec/image/png/common/src/pngconf.h',
          '<(UICPATH)/codec/image/png/common/src/pngread.c',
          '<(UICPATH)/codec/image/png/common/src/pngerror.c',
          '<(UICPATH)/codec/image/png/enc/src/uic_png_enc.cpp',
          '<(UICPATH)/codec/image/png/enc/include/uic_png_enc.h',
#'<(UICPATH)/codec/image/jpeg/common/src/',
          '<(UICPATH)/core/uic/include/uic_addr_arith.h',
          '<(UICPATH)/core/uic/include/uic_attachable_buffer.h',
          '<(UICPATH)/core/uic/include/uic_base_image_codec.h',
          '<(UICPATH)/core/uic/include/uic_base_image_decoder.h',
          '<(UICPATH)/core/uic/include/uic_base_image_encoder.h',
          '<(UICPATH)/core/uic/include/uic_base_stream_diagn.h',
          '<(UICPATH)/core/uic/include/uic_base_stream.h',
          '<(UICPATH)/core/uic/include/uic_base_stream_input.h',
          '<(UICPATH)/core/uic/include/uic_base_stream_output.h',
          '<(UICPATH)/core/uic/include/uic_defs.h',
          '<(UICPATH)/core/uic/include/uic_exc_status.h',
          '<(UICPATH)/core/uic/include/uic_fixed_array.h',
          '<(UICPATH)/core/uic/include/uic_fixed_buffer.h',
          '<(UICPATH)/core/uic/include/uic_general_algorithm.h',
          '<(UICPATH)/core/uic/include/uic_geometry.h',
          '<(UICPATH)/core/uic/include/uic_image_converter.h',
          '<(UICPATH)/core/uic/include/uic_image.h',
          '<(UICPATH)/core/uic/include/uic_math.h',
          '<(UICPATH)/core/uic/include/uic_new.h',
          '<(UICPATH)/core/uic/src/uic_image_converter.cpp',
          '<(UICPATH)/core/uic/src/uic_image.cpp',
          '<(UICPATH)/core/uic/src/uic_new.cpp',
          '<(UICPATH)/io/uic_io/include/membuffin.h',
          '<(UICPATH)/io/uic_io/include/membuffout.h',
          '<(UICPATH)/io/uic_io/include/stdfilein.h',
          '<(UICPATH)/io/uic_io/include/stdfileout.h',
          '<(UICPATH)/io/uic_io/src/membuffin.cpp',
          '<(UICPATH)/io/uic_io/src/membuffout.cpp',
          '<(UICPATH)/io/uic_io/src/stdfilein.cpp',
          '<(UICPATH)/io/uic_io/src/stdfileout.cpp',
      ],
      'libraries': ['-lboost_thread', '-lippch_l', '-lippdc_l', '-lippcc_l', '-lippcv_l', '-lippj_l', '-lippi_l', '-lipps_l', '-lippcore_l',
                    '-lpthread', '-liomp5', '-z nodefaultlib', '-nostdlib', '-ltbb'
                   '-L/opt/intel/lib/intel64',
                   '-L/opt/intel/ipp/lib/intel64' ],
      'direct_dependent_settings': {
        'include_dirs': ['/opt/intel/include','/opt/intel/ipp/include',
                       '<(UICPATH)/core/uic/include', '<(UICPATH)/io/uic_io/include',
                       '<(UICPATH)/codec/image/jpeg/dec/include', '<(UICPATH)/codec/image/jpeg/common/include', '<(UICPATH)/codec/image/jpeg/enc/include',
                       '<(UICPATH)/codec/image/png/dec/include', '<(UICPATH)/codec/image/png/common/include', '<(UICPATH)/codec/image/png/enc/include'],
        'libraries': ['-lippi_l', '-lippj_l', '-lipps_l',
                   '-L/opt/intel/lib/intel64',
                   '-L/opt/intel/ipp/lib/intel64' ],
      }
    }
  ]
}
