<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/n/apps/photo/modules/flashUploaderAndSend/flashUploaderSeed.js?ver=$revxxx$"/>
<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/n/apps/photo/modules/flashUploaderAndSend/flash-upload-all-min.css?ver=$revxxx$"/>
<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/n/apps/photo/modules/photo-view/photo-view-all-min.css?ver=$revxxx$"/>
<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/n/apps/photo/modules/photo-view/js/photoViewerSparta.js?ver=$revxxx$"/>
<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/jspro/album/commentManage.js?ver=$revxxx$"/>
<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/csspro/module/replies.css?ver=$revxxx$"/>
<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/n/apps/photo/modules/libs/tagPhoto-div.js?ver=$revxxx$"/> 
<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/n/apps/photo/modules/photo-view/js/photoViewerCtr.js?ver=$revxxx$"/> 
<input type="hidden" name="photoStatic" value="${applicationScope.urlSmallStatic}/n/apps/photo/flashUploaderWithSend.js?ver=$revxxx$"/>


