<font color=red>开心狗狗活动调试 </font><br />
<hr />
<!-- <a href="/views/activity/dogbonus/d_dog_bonus.jsp">看库存</a> | --> 
<a href="/views/activity/dogbonus/d_dog_account.jsp">看账户</a> | 
<a href="/views/activity/dogbonus/d_dog_invite.jsp">看邀请</a> | 
<!-- <a href="/views/activity/dogbonus/d_dog_award.jsp">看中奖</a> | --> 
<a href="/views/activity/dogbonus/d_dog_link.jsp">看邀请链接</a> | 
<a href="/views/activity/dogbonus/d_dog_linkids.jsp">看谁们可以得到邀请链接</a> | <br />
<hr />
<br />