/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "ping_constants.h"

namespace com { namespace renren { namespace ad { namespace ping {

const pingConstants g_ping_constants;

pingConstants::pingConstants() {
}

}}}} // namespace

