#!/bin/bash
PROTO_PATH="proto"
PROTO_GENDIR="target/generated/protobuf"
PROTO_HOME="/usr/local/distcache-dev"
PROTO_INCLUDE="$PROTO_HOME/include:$PROTO_PATH"
PROTO_CMD_JAVA="$PROTO_HOME/bin/protoc -I$PROTO_INCLUDE --java_out=$PROTO_GENDIR"
PROTO_LIST=$(find $PROTO_PATH -name "*.proto")

mkdir -p $PROTO_GENDIR
for PRO in $PROTO_LIST
do
  echo "Generating $PRO "
  $PROTO_CMD_JAVA $PRO
  if [ $? -ne 0 ]
	then
		exit 1
	fi
done

exit 0
