#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadUser > ./log/user.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadUserConfigR > ./log/userconfigr.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadUserState > ./log/userstate.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadUserStateR > ./log/userstater.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadUserNetwork > ./log/usernetwork.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadRecentContact > ./log/recentcontact.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadBlogFootprintL > ./log/blogfootprint.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadFootprintN > ./log/footprint.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadNotifyRpl > ./log/notifyrpl.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadVisitCount > ./log/visitcount.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadUserCount > ./log/usercount.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadBuddyCore > ./log/buddycore.log 2>&1 &
nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadBuddyGroup > ./log/buddygroup.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadUserBase > ./log/userbase.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadBuddyApplyCache > ./log/buddyapplycache.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadBuddyCacheByName > ./log/buddycachebyname.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadFriendDist > ./log/frienddist.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadFriendFinderReplica > ./log/friendfinderreplica.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadOfferFriendsReplica > ./log/offerfriendsreplica.log 2>&1 &
#nohup ~/java/bin/java -cp ".:/opt/Ice-3.3/lib/Ice.jar:lib/*" xce.tools.objectcache.ObjectCacheShell PreloadFriendFinderByActiveUser > ./log/friendfinderbyactiveuser.log 2>&1 &
