<font color=red>人人抽奖活动调试 </font><br />
<hr />
<a href="/views/activity/recallbonus/d_rc_bonus.jsp">看库存</a> | 
<a href="/views/activity/recallbonus/d_rc_account.jsp">看账户</a> | 
<a href="/views/activity/recallbonus/d_rc_invite.jsp">看邀请</a> | 
<a href="/views/activity/recallbonus/d_rc_award.jsp">看中奖</a> | 
<a href="/views/activity/recallbonus/d_rc_link.jsp">看邀请链接</a> | 
<a href="/views/activity/recallbonus/d_rc_linkids.jsp">看谁们可以得到邀请链接</a> |
<a href="/views/activity/recallbonus/d_rc_awardyestoday.jsp">看昨天谁中奖了</a> | 
<a href="/views/activity/recallbonus/d_rc_award_send.jsp">危险操作，不懂勿进</a> | 
<br />
<hr />
<br />