<%@ page contentType="text/html;charset=UTF-8" session="false" %>
<section data-type="work">
	<dl class="f-s">
		<dt><label for="">我的单位：</label></dt>
		<dd>
			<input class="inputtext" id="workplaceAC" data-type="name" data-tip="xxx" />
		</dd>
	</dl>
	<dl>
		<dt><label for="">当前所在地：</label></dt>
		<dd>
			<select id="city-main"><option>省份</option></select>
			<select id="city-sub" data-tip="xxx"><option>城市</option></select>
		</dd>
	</dl>
</section>