<%@ page contentType="text/html;charset=UTF-8" session="false" %>
<section data-type="tech">
	<dl class="f-s">
		<dt><label for="">中专：</label></dt>
		<dd>
			<input class="inputtext s-select s-tech" data-type="name" data-tip="xxx" />
		</dd>
	</dl>
	<dl>
		<dt><label for="">入学年份：</label></dt>
		<dd>
			<select class="y-comp" data-type="year" data-tip="xxx">
				<option>--</option>
			</select>
		</dd>
	</dl>
</section>