package com.xiaonei.xce.dbpool;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;

public class PooledConnection implements Connection {
	private final Connection _realConn;
	private final ConnectionPool _pool;

	public PooledConnection(Connection realconn, ConnectionPool pool) {
		_realConn = realconn;
		_pool = pool;
	}

	public Connection getRealConnection() {
		return _realConn;
	}
	
	@Override
	public void clearWarnings() throws SQLException {
		_realConn.clearWarnings();
	}

	@Override
	public void close() throws SQLException {
		_pool.returnObject(this);
	}

	@Override
	public void commit() throws SQLException {
		_realConn.commit();
	}

	@Override
	public Array createArrayOf(String typeName, Object[] elements)
			throws SQLException {
		return _realConn.createArrayOf(typeName, elements);
	}

	@Override
	public Blob createBlob() throws SQLException {
		return _realConn.createBlob();
	}

	@Override
	public Clob createClob() throws SQLException {
		return _realConn.createClob();
	}

	@Override
	public NClob createNClob() throws SQLException {
		return _realConn.createNClob();
	}

	@Override
	public SQLXML createSQLXML() throws SQLException {
		return _realConn.createSQLXML();
	}

	@Override
	public Statement createStatement() throws SQLException {
		return _realConn.createStatement();
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency)
			throws SQLException {
		return _realConn.createStatement(resultSetType, resultSetConcurrency);
	}

	@Override
	public Statement createStatement(int resultSetType,
			int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return _realConn.createStatement(resultSetType, resultSetConcurrency,
				resultSetHoldability);
	}

	@Override
	public Struct createStruct(String typeName, Object[] attributes)
			throws SQLException {
		return _realConn.createStruct(typeName, attributes);
	}

	@Override
	public boolean getAutoCommit() throws SQLException {
		return _realConn.getAutoCommit();
	}

	@Override
	public String getCatalog() throws SQLException {
		return _realConn.getCatalog();
	}

	@Override
	public Properties getClientInfo() throws SQLException {
		return _realConn.getClientInfo();
	}

	@Override
	public String getClientInfo(String name) throws SQLException {
		return _realConn.getClientInfo(name);
	}

	@Override
	public int getHoldability() throws SQLException {
		return _realConn.getHoldability();
	}

	@Override
	public DatabaseMetaData getMetaData() throws SQLException {
		return _realConn.getMetaData();
	}

	@Override
	public int getTransactionIsolation() throws SQLException {
		return _realConn.getTransactionIsolation();
	}

	@Override
	public Map<String, Class<?>> getTypeMap() throws SQLException {
		return _realConn.getTypeMap();
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		return _realConn.getWarnings();
	}

	@Override
	public boolean isClosed() throws SQLException {
		return _realConn.isClosed();
	}

	@Override
	public boolean isReadOnly() throws SQLException {
		return _realConn.isReadOnly();
	}

	@Override
	public boolean isValid(int timeout) throws SQLException {
		return _realConn.isValid(timeout);
	}

	@Override
	public String nativeSQL(String sql) throws SQLException {
		return _realConn.nativeSQL(sql);
	}

	@Override
	public CallableStatement prepareCall(String sql) throws SQLException {
		return _realConn.prepareCall(sql);
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType,
			int resultSetConcurrency) throws SQLException {
		return _realConn.prepareCall(sql, resultSetType, resultSetConcurrency);
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType,
			int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return _realConn.prepareCall(sql, resultSetType, resultSetConcurrency,
				resultSetHoldability);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return _realConn.prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
			throws SQLException {
		return _realConn.prepareStatement(sql, autoGeneratedKeys);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
			throws SQLException {
		return _realConn.prepareStatement(sql, columnIndexes);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames)
			throws SQLException {
		return _realConn.prepareStatement(sql, columnNames);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType,
			int resultSetConcurrency) throws SQLException {
		return _realConn.prepareStatement(sql, resultSetType,
				resultSetConcurrency);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType,
			int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return _realConn.prepareStatement(sql, resultSetType,
				resultSetConcurrency, resultSetHoldability);
	}

	@Override
	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		_realConn.releaseSavepoint(savepoint);
	}

	@Override
	public void rollback() throws SQLException {
		_realConn.rollback();
	}

	@Override
	public void rollback(Savepoint savepoint) throws SQLException {
		_realConn.rollback(savepoint);
	}

	@Override
	public void setAutoCommit(boolean autoCommit) throws SQLException {
		_realConn.setAutoCommit(autoCommit);
	}

	@Override
	public void setCatalog(String catalog) throws SQLException {
		_realConn.setCatalog(catalog);
	}

	@Override
	public void setClientInfo(Properties properties)
			throws SQLClientInfoException {
		_realConn.setClientInfo(properties);
	}

	@Override
	public void setClientInfo(String name, String value)
			throws SQLClientInfoException {
		_realConn.setClientInfo(name, value);
	}

	@Override
	public void setHoldability(int holdability) throws SQLException {
		_realConn.setHoldability(holdability);
	}

	@Override
	public void setReadOnly(boolean readOnly) throws SQLException {
		_realConn.setReadOnly(readOnly);
	}

	@Override
	public Savepoint setSavepoint() throws SQLException {
		return _realConn.setSavepoint();
	}

	@Override
	public Savepoint setSavepoint(String name) throws SQLException {
		return _realConn.setSavepoint(name);
	}

	@Override
	public void setTransactionIsolation(int level) throws SQLException {
		_realConn.setTransactionIsolation(level);
	}

	@Override
	public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
		_realConn.setTypeMap(map);
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return _realConn.isWrapperFor(iface);
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		return _realConn.unwrap(iface);
	}

}
