<%@ page pageEncoding="UTF-8" %>
				</div>
			</div>
		</div>
	</div>
	<div id="footer">
		<div class="copyright">
			<span class="float-right">
				<a href="http://support.kaixin.com/GetGuestbookList.do">客服</a>
				<span class="pipe">|</span><a href="http://kaixin.com/info/Help.do">帮助</a>
			</span>
			<span>千橡公司 <span title="revision$revxxx$; ${applicationScope.hostName}">&copy;</span> 2012</span>
		</div>
	</div>
	<div class="hidden-area"></div>
<script src="${applicationScope.urlStatic}/kaixin/utm/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
(function()
{
    var p = 1;
    if( parseInt( Math.random() * ( 10 - p ) ) + 1 == 1 )
    {
        _userv = 2;
        urchinTracker();
    }
})();
</script>
