<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<div class="mainbox" style="background:none;">
    <!--head-->
	<div id="headerpro" class="clearfix">
	    <div id="navigation" >           
	        <a href="http://home.kaixin.com/Home.do" title="开心网" style="float:left"><img src="${applicationScope.urlStatic}/kaixin/imgpro/logo/logo_new_login.png" alt="开心网(Logo)"/></a>       
	        <ul class="nav-right">
	            <li><a href="http://reg.kaixin.com/register.do?ss=10101"> 注册</a></li>
	            <li><a href="${applicationScope.urlLogin}/GLogin.do"> 请登录</a></li>
	            <li><a href="http://kaixin.com/info/Help.do"> 帮助</a></li>
	        </ul>
	    </div>
	</div>
