        <div id="navBar" class="menu-bar">
                <div class="navigation-wrapper">
                        <div class="navigation clearfix">
                                <logo:logotag/>	
                                <div class="nav-body clearfix">
                                        <div class="nav-other">
                                                <div class="menu">
                                                        <div class="menu-title last">
                                                                <a href="http://www.${applicationScope.sysdomain}/Logout.do">退出</a>
                                                        </div>
                                                </div>
                                        </div>
                                </div>
                        </div>
                </div>
        </div>
        