package com.xiaonei.reg.register.constants;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class XIdBlackList implements Serializable {

    private static final long serialVersionUID = -2976815115344429128L;
    private static final boolean USED = true;
    private static Map<String, Boolean> map = null;

    static {
        map = new HashMap<String, Boolean>();
        map.put("gay", USED);
        map.put("uck", USED);
        map.put("oai", USED);
        map.put("onima", USED);
        map.put("daozhonggong", USED);
        map.put("daogongchandang", USED);
        map.put("vernmentgovernment", USED);
        map.put("JT", USED);
        map.put("uerkaixi", USED);
        map.put("harter08", USED);
        map.put("8Charter", USED);
        map.put("oyaominzhu", USED);
        map.put("4memo", USED);
        map.put("alungong", USED);
        map.put("iusishijian", USED);
        map.put("4shijian", USED);
        map.put("iusixuechao", USED);
        map.put("4xuechao", USED);
        map.put("4yundong", USED);
        map.put("iusiyundong", USED);
        map.put("uanghaishijian", USED);
        map.put("iananmendadusha", USED);
        map.put("iananmendusha", USED);
        map.put("iananmenshijian", USED);
        map.put("izangduli", USED);
        map.put("alailama", USED);
        map.put("ajiu", USED);
        map.put("angdu", USED);
        map.put("henxitong", USED);
        map.put("henzongtong", USED);
        map.put("hihaotian", USED);
        map.put("hihua", USED);
        map.put("ajiyuan", USED);
        map.put("ajiyuanxinwenwang", USED);
        map.put("ajiyuan", USED);
        map.put("azhongguoluntan", USED);
        map.put("azhonghualuntan", USED);
        map.put("ongbeiduli", USED);
        map.put("ongfanghongshikong", USED);
        map.put("ongtueqisitan", USED);
        map.put("ulitaiwanhui", USED);
        map.put("agong", USED);
        map.put("aidu", USED);
        map.put("ongzhi", USED);
        map.put("ihongzhi", USED);
        map.put("inghui", USED);
        map.put("inghuinews", USED);
        map.put("reechina", USED);
        map.put("izongtong", USED);
        map.put("dh", USED);
        map.put("ipeng", USED);
        map.put("iruihuan", USED);
        map.put("anrenlei", USED);
        map.put("anshehui", USED);
        map.put("enlei", USED);
        map.put("ongchan", USED);
        map.put("ongdang", USED);
        map.put("ongjun", USED);
        map.put("ongdengqu", USED);
        map.put("uangju", USED);
        map.put("aizidang", USED);
        map.put("huibian", USED);
        map.put("engqinghong", USED);
        map.put("humao", USED);
        map.put("iangchunyun", USED);
        map.put("iangdu", USED);
        map.put("iangfa", USED);
        map.put("ijinai", USED);
        map.put("ilanju", USED);
        map.put("ilanqing", USED);
        map.put("ipeng", USED);
        map.put("iruihuan", USED);
        map.put("ipeng", USED);
        map.put("iusi", USED);
        map.put("vxiulian", USED);
        map.put("angdu", USED);
        map.put("ongbeiduli", USED);
        map.put("ulitaiwanhui", USED);
        map.put("uogan", USED);
        map.put("engdu", USED);
        map.put("engguduli", USED);
        map.put("ianqichen", USED);
        map.put("iaoshi", USED);
        map.put("huibian", USED);
        map.put("aidu", USED);
        map.put("aiwanduli", USED);
        map.put("iangdu", USED);
        map.put("engdu", USED);
        map.put("engguduli", USED);
        map.put("aiwanduli", USED);
        map.put("aizidang", USED);
        map.put("izangduli", USED);
        map.put("aizidang", USED);
        map.put("enjiabao", USED);
        map.put("ubangguo", USED);
        map.put("uguanzheng", USED);
        map.put("izangduli", USED);
        map.put("ucaihou", USED);
        map.put("uechao", USED);
        map.put("J", USED);
        map.put("J", USED);
        map.put("J", USED);
        map.put("engpeiyan", USED);
        map.put("engqinghong", USED);
        map.put("haoziyang", USED);
        map.put("honggong", USED);
        map.put("honggong", USED);
        map.put("honghuaminguo", USED);
        map.put("J", USED);
        map.put("angdu", USED);
        map.put("hulin", USED);
        map.put("humao", USED);
        map.put("humao", USED);
        map.put("humao", USED);
        map.put("alu", USED);
        map.put("alun", USED);
        map.put("alundafa", USED);
        map.put("a", USED);
        map.put("lg", USED);
        map.put("uck", USED);
        map.put("ongzhi", USED);
        map.put("ypermart.net", USED);
        map.put("ihongzhi", USED);
        map.put("henshanren", USED);
        map.put("huanfalun", USED);
        map.put("iangdu", USED);
        map.put("engdu", USED);
        map.put("engguduli", USED);
        map.put("ichuangdu", USED);
        map.put("aiwandu", USED);
        map.put("aizidang", USED);
        map.put("hangfang", USED);
        map.put("bajiu", USED);
        map.put("zangdu", USED);
        map.put("chenxitong", USED);
        map.put("chenzongtong", USED);
        map.put("chihaotian", USED);
        map.put("chihua", USED);
        map.put("dajiyuan", USED);
        map.put("dajiyuanxinwenwang", USED);
        map.put("dajiyuan", USED);
        map.put("dazhongguoluntan", USED);
        map.put("dazhonghualuntan", USED);
        map.put("dongbeiduli", USED);
        map.put("dongfanghongshikong", USED);
        map.put("dongtueqisitan", USED);
        map.put("dulitaiwanhui", USED);
        map.put("fagong", USED);
        map.put("fagong", USED);
        map.put("taidu", USED);
        map.put("lizongtong", USED);
        map.put("ldh", USED);
        map.put("lipeng", USED);
        map.put("liruihuan", USED);
        map.put("fanrenlei", USED);
        map.put("fanshehui", USED);
        map.put("fenlei", USED);
        map.put("gongchan", USED);
        map.put("gongdang", USED);
        map.put("gongjun", USED);
        map.put("hongdengqu", USED);
        map.put("huangju", USED);
        map.put("taizidang", USED);
        map.put("shuibian", USED);
        map.put("zengqinghong", USED);
        map.put("zhumao", USED);
        map.put("jiangchunyun", USED);
        map.put("jiangdu", USED);
        map.put("jiangfa", USED);
        map.put("lijinai", USED);
        map.put("lilanju", USED);
        map.put("lilanqing", USED);
        map.put("lipeng", USED);
        map.put("liruihuan", USED);
        map.put("lipeng", USED);
        map.put("liusi", USED);
        map.put("lvxiulian", USED);
        map.put("zangdu", USED);
        map.put("dongbeiduli", USED);
        map.put("dulitaiwanhui", USED);
        map.put("luogan", USED);
        map.put("mengdu", USED);
        map.put("mengguduli", USED);
        map.put("qianqichen", USED);
        map.put("qiaoshi", USED);
        map.put("shuibian", USED);
        map.put("taidu", USED);
        map.put("taiwanduli", USED);
        map.put("jiangdu", USED);
        map.put("mengdu", USED);
        map.put("mengguduli", USED);
        map.put("taiwanduli", USED);
        map.put("taizidang", USED);
        map.put("xizangduli", USED);
        map.put("taizidang", USED);
        map.put("wenjiabao", USED);
        map.put("wubangguo", USED);
        map.put("wuguanzheng", USED);
        map.put("xizangduli", USED);
        map.put("xucaihou", USED);
        map.put("xuechao", USED);
        map.put("zengpeiyan", USED);
        map.put("zengqinghong", USED);
        map.put("zhaoziyang", USED);
        map.put("zhonggong", USED);
        map.put("zhonggong", USED);
        map.put("zhonghuaminguo", USED);
        map.put("zangdu", USED);
        map.put("zhulin", USED);
        map.put("zhumao", USED);
        map.put("zhumao", USED);
        map.put("zhumao", USED);
        map.put("jiangdu", USED);
        map.put("mengdu", USED);
        map.put("mengguduli", USED);
        map.put("sichuangdu", USED);
        map.put("taiwandu", USED);
        map.put("taizidang", USED);
        map.put("shangfang", USED);
        map.put("hongzhi ", USED);
        map.put("lihongzhi ", USED);
        map.put("minghui ", USED);
        map.put("minghuinews ", USED);
        map.put("freechina ", USED);
        map.put("4-Jun ", USED);
        map.put("fuck ", USED);
        map.put("shit ", USED);
        map.put("falu ", USED);
        map.put("falun ", USED);
        map.put("falundafa ", USED);
        map.put("flg ", USED);
        map.put("fuck ", USED);
        map.put("hongzhi ", USED);
        map.put("hypermart.net ", USED);
        map.put("lihongzhi ", USED);
        map.put("zhenshanren ", USED);
        map.put("zhuanfalun ", USED);

    }

    public static Map<String, Boolean> getBlackList() {
        return map;
    }
}
