<div id="publisher_statusContent" class="status-composer">
	<input class="input-button gray float-right" tabindex="3" onclick="$('publisherModule').hide();$('publisher_statusTab').className=''" type="submit" value="取消" />
	<input type="button" id="publisher_statusSubmit" tabindex="2" class="input-button float-right" value="提交" />
	<input id="publisher_myStatus" tabindex="1" type="text" class="input-text input-status" value="输入你的最新状态..." /><small id="publisher_statusInputCount" class="count"><span id="left">0</span>/<span>70</span></small>
	<input type="hidden" name="tsc" id="publisher_status_tsc" />
</div>