<%@ page pageEncoding="UTF-8" %>
<div id="highSchoolList" style="display:none;" class="popup-wrapper">
    <div class="popup-content">
        <ul id="popup-province-hs">
        </ul>
        <ul id="popup-unis-hs">
        </ul>
        <input id="highSchoolCloseButton" type="button" class="canbutton" value="关闭窗口"/>
    </div>
<!--[if lte IE 6.5]><iframe></iframe><![endif]-->
</div>
<script>
highschooltabs.changeCountry('0');
</script>