<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
	<link href="${applicationScope.urlSmallStatic}/favicon-${domainIdentified["siteNameAbbr"]}.ico?ver=2" rel="shortcut icon" type="image/x-icon" />
	<link href="${applicationScope.urlSmallStatic}/renren_logo_apple.png" rel="apple-touch-icon" />
	<link href="${applicationScope.urlSmallStatic}/csspro/base/layout.css?ver=$revxxx$" rel="stylesheet" type="text/css" media="all" />
	<script type="text/javascript" src="${applicationScope.urlSmallStatic}/jspro/base.js?ver=$revxxx$"></script>    
    <script type="text/javascript">
    XN.get_check='${requestScope.postFormSession}';
	XN.get_check_x = '${requestScope._rtk}';
    XN.getFileVersion(
    [
        '${applicationScope.urlSmallStatic}/csspro/apps/profile.css?ver=$revxxx$',
        '${applicationScope.urlSmallStatic}/jspro/xn.app.recommendFriend.js?ver=$revxxx$',
        '${applicationScope.urlSmallStatic}/jspro/xn.ui.pager.js?ver=$revxxx$',
        '${applicationScope.urlSmallStatic}/jspro/xn.ui.multiFriendSelectorBox.js?ver=$revxxx$',
        '${applicationScope.urlSmallStatic}/csspro/module/friendSelector.css?ver=$revxxx$',
        '${applicationScope.urlSmallStatic}/jspro/editor/tiny_mce.js?ver=$revxxx$',
        '${applicationScope.urlSmallStatic}/js/inCityArray.js?ver=$revxxx$',
        '${applicationScope.urlSmallStatic}/js/cityArray.js?ver=$revxxx$',
        '${applicationScope.urlSmallStatic}/allunivlist.js?ver=$revxxx$'
    ]);    
    </script>
    <!-- flow head -->
	<%@ include file="/inc/patch.inc" %>