<%@ page contentType="text/html;charset=UTF-8" %>
<%
//---------------------------------------------------------------------------------------------------
//-- 大学院系组件-/inc/
//-- 支持同一个页面显示多个大学院系组件，
//---------------------------------------------------------------------------------------------------
%>
<div id="univ_dept_div" style="display:none;">
	<table><tbody><tr><td><input type="button" class="inputbutton" value="关闭"/></td></tr></tbody></table>
	<ul style="display:block;" id="univ_dept_component_ul">
		&nbsp;
	</ul>
</div>