<%@ page pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://struts.apache.org/tags-html" prefix="html"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/jspro/xn.app.poke.js?ver=$revxxx$"></script>
<link href="${applicationScope.urlSmallStatic}/csspro/module/poke.css?ver=$revxxx$" rel="stylesheet" type="text/css" media="all"/>