<%@ page pageEncoding="UTF-8" %>
<div class="xp-n3">
<IFRAME id="p44" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=200 HEIGHT=300 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=83">
<NOSCRIPT><A HREF="http://gg.${applicationScope.domain}/direct.jsp?p=83"><IMG SRC="http://gg.${applicationScope.domain}/view.jsp?p=83" WIDTH=200 HEIGHT=300 BORDER=0></a></NOSCRIPT></IFRAME>
</div>