<%@ page pageEncoding="UTF-8" %>
<div class="xp-n">
<IFRAME id="p44" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=120 HEIGHT=280 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=82">
<NOSCRIPT><A HREF="http://gg.${applicationScope.domain}/direct.jsp?p=82"><IMG SRC="http://gg.${applicationScope.domain}/view.jsp?p=82" WIDTH=120 HEIGHT=280 BORDER=0></a></NOSCRIPT></IFRAME>
</div>

