<%@ page pageEncoding="UTF-8" %>
<div class="block announcement link">
<h3>站内活动</h3>
<div class="blockcont text">
<IFRAME id="200" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=200">
</IFRAME>
<IFRAME id="201" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=201">
</IFRAME>
</div>
</div>
<div class="block announcement link">
<h3>推荐日志</h3>
<div class="blockcont text">
<IFRAME id="202" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=202">
</IFRAME>
<IFRAME id="203" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=203">
</IFRAME>
<IFRAME id="204" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=204">
</IFRAME>
<IFRAME id="205" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=205">
</IFRAME>
</div>
</div>
<div class="block announcement link">
<h3>推荐相册</h3>
<div class="blockcont text">
<IFRAME id="206" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=206">
</IFRAME>
<IFRAME id="207" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=207">
</IFRAME>
<IFRAME id="208" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=208">
</IFRAME>
<IFRAME id="209" MARGINHEIGHT=0 MARGINWIDTH=0 FRAMEBORDER=0 WIDTH=100% HEIGHT=16 SCROLLING=NO SRC="http://gg.${applicationScope.domain}/view.jsp?p=209">
</IFRAME>
</div>
</div>