<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/univscript.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/schlist.js?ver=0.2"></script>
	<div class="provinces" style="border-right:1px solid #3B5888; text-align:right; margin-left:8px;" >
		<div id="anhui"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('anhui',tabs.changeTab_cb)">安徽</a></div>
		<div id="aomen"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('aomen',tabs.changeTab_cb)">澳门</a></div>
		<%--div id="aomen">澳门</div--%>
		<div id="beijing"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('beijing',tabs.changeTab_cb)">北京</a></div>
		<div id="chongqing"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('chongqing',tabs.changeTab_cb)">重庆</a></div>
		<div id="fujian"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('fujian',tabs.changeTab_cb)">福建</a></div>
		<div id="gansu"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('gansu',tabs.changeTab_cb)">甘肃</a></div>
		<div id="guangdong"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('guangdong',tabs.changeTab_cb)">广东</a></div>
		<div id="guangxi"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('guangxi',tabs.changeTab_cb)">广西</a></div>
		<div id="guizhou"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('guizhou',tabs.changeTab_cb)">贵州</a></div>
		<div id="hainan"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('hainan',tabs.changeTab_cb)">海南</a></div>
		<div id="hebei"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('hebei',tabs.changeTab_cb)">河北</a></div>
		<div id="henan"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('henan',tabs.changeTab_cb)">河南</a></div>
		<div id="hlj"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('hlj',tabs.changeTab_cb)">黑龙江</a></div>
		<div id="hubei"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('hubei',tabs.changeTab_cb)">湖北</a></div>
		<div id="hunan"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('hunan',tabs.changeTab_cb)">湖南</a></div>
		<div id="jilin"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('jilin',tabs.changeTab_cb)">吉林</a></div>
		<div id="jiangsu"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('jiangsu',tabs.changeTab_cb)">江苏</a></div>
	</div>
	<div id="tabPan"></div>
	<div class="provinces" style="border-left:1px solid #3B5888; text-align:left;" >
		<div id="jiangxi"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('jiangxi',tabs.changeTab_cb)">江西</a></div>
		<div id="liaoning"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('liaoning',tabs.changeTab_cb)">辽宁</a></div>
		<div id="neimeng"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('neimeng',tabs.changeTab_cb)">内蒙</a></div>
		<div id="ningxia"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('ningxia',tabs.changeTab_cb)">宁夏</a></div>
		<div id="qinghai"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('qinghai',tabs.changeTab_cb)">青海</a></div>
		<div id="shandong"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('shandong',tabs.changeTab_cb)">山东</a></div>
		<div id="taiyuan"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('taiyuan',tabs.changeTab_cb)">山西</a></div>
		<div id="xian"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('xian',tabs.changeTab_cb)">陕西</a></div>
		<div id="shanghai"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('shanghai',tabs.changeTab_cb)">上海</a></div>
		<div id="sichuan"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('sichuan',tabs.changeTab_cb)">四川</a></div>
		<div id="taiwan"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('taiwan',tabs.changeTab_cb)">台湾</a></div>
		<%--div id="taiwan">台湾</div--%>
		<div id="tianjin"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('tianjin',tabs.changeTab_cb)">天津</a></div>
		<div id="xizang"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('xizang',tabs.changeTab_cb)">西藏</a></div>
		<div id="xianggang"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('xianggang',tabs.changeTab_cb)">香港</a></div>
		<div id="xinjiang"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('xinjiang',tabs.changeTab_cb)">新疆</a></div>
		<%--div id="xianggang">香港</div --%>
>
		<div id="yunnan"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('yunnan',tabs.changeTab_cb)">云南</a></div>
		<div id="zhejiang"><a href="#" onmouseover="return tabs.mouseIn()" onmouseout="return tabs.mouseOut()" onclick="return tabs.changeTab('zhejiang',tabs.changeTab_cb)">浙江</a></div>
	</div>
<script type="text/javascript">
	tabs.changeTab('beijing',tabs.changeTab_cb)
</script>
