<div id="simpleEditPan">
<textarea name="body" id="cmtbody" cols="100%" rows="6" style="display:none"></textarea>
<iframe src="/pages/editor/editor.htm?target=cmtbody&btn=bold,italic,color,link,face&ver=$revxxx$" frameborder="0" id="simplerte" class="simplerte"></iframe>
<script type="text/javascript">
//edited by ray 4 the short cut submit
function quickSendEditorCon() {
	getEl("editorFormBtn").click();
}
</script>
</div>
