
SET (BASE_TMP_DIR "tmp")

SET (BUSINESS_DIR "logging/Counting")
SET (REPOS_DIR "../${BUSINESS_DIR}")
STRING (REPLACE "/" "_" BUSINESS_NAME ${BUSINESS_DIR})

GENERATE_SLICE2CPP_RULES ("${REPOS_DIR}/slice"
${BASE_TMP_DIR}/${BUSINESS_DIR}
${BUSINESS_NAME}_slice_generated_sources
${BUSINESS_NAME}_slice_generated_headers "Counting.ice")

INCLUDE_DIRECTORIES (${BASE_TMP_DIR}/${BUSINESS_DIR})
ADD_LIBRARY (${BUSINESS_NAME}_slice ${${BUSINESS_NAME}_slice_generated_sources})

AUX_SOURCE_DIRECTORY ("${REPOS_DIR}/server/" BUILD_${BUSINESS_NAME}_SERVER_CPP_SOURCE)
ADD_LIBRARY ("Counting" SHARED EXCLUDE_FROM_ALL ${BUILD_${BUSINESS_NAME}_SERVER_CPP_SOURCE})
TARGET_LINK_LIBRARIES( "Counting" IceExt UtilCxx )

AUX_SOURCE_DIRECTORY ("${REPOS_DIR}/client/" BUILD_${BUSINESS_NAME}_CLIENT_CPP_SOURCE)
ADD_EXECUTABLE ("CountingClient" EXCLUDE_FROM_ALL ${BUILD_${BUSINESS_NAME}_CLIENT_CPP_SOURCE})
TARGET_LINK_LIBRARIES ("CountingClient" IceExt UtilCxx)

