ADD_SERVICE("app/FootprintUnite/FootprintFacade" "FootprintFacade" OceCxxAdapterLoveFootprintByInterviewerAdapter OceCxxAdapterLoveFootprintByIntervieweeAdapter OceCxxAdapterVisitFootprintAdapter OceCxxAdapterHomeFootprintAdapter OceCxxAdapterFootprintFacadeAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceBatchUpdater OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/FootprintUnite/HomeFootprint" "HomeFootprint" ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater  OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/UgcFootprint" "UgcFootprint" ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/FootprintUnite/CommonFootprint" "LoveFootprint" ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

#ADD_SERVICE("app/FootprintFilter/src" "FootprintFilterN" OceSliceFootprint OceSliceFootprintNew OceSliceFootprintFilter OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater ReplicaCluster IceExt  OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/FootprintUgc/src" "BlogFootprintL" ReplicaCluster OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceFootprint OceSliceFootprintNew OceSliceFootprintFilter OceSliceUser OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/FootprintNew/src" "Footprint" ReplicaCluster OceSliceFootprintNew OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/RecentContact/src" "RecentContact" ReplicaCluster OceSliceRecentContact OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/Bulletin/admin" "BulletinAdmin" OceCxxAdapterBulletinAdapter OceSliceBulletin ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)
    
ADD_DC_SERVICE("app/Bulletin/manager" "BulletinManager" OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterUserBornAdapter OceCxxAdapterUserStageAdapter OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceCxxAdapterUserDescAdapter OceCxxAdapterUserNetworkAdapter OceSliceActiveTrack OceSliceXceLogger OceSliceUserCache OceSliceUserBase OceSliceUserDesc OceSliceUserNetwork OceSliceBulletin ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)

ADD_SERVICE("app/Tips/admin" "TipsAdmin" OceCxxAdapterTipsAdapter OceSliceTips ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)
    
ADD_DC_SERVICE("app/Tips/manager" "TipsManager" OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterUserBornAdapter OceCxxAdapterUserStageAdapter OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceCxxAdapterUserDescAdapter OceCxxAdapterUserNetworkAdapter OceSliceActiveTrack OceSliceXceLogger OceSliceUserCache OceSliceUserBase OceSliceUserDesc OceSliceUserNetwork OceSliceTips ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)
ADD_DC_SERVICE("app/ILikeIt/logic" "ILikeItLogic" OceCxxAdapterILikeItCacheAdapter OceCxxAdapterILikeItLogicAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter ReplicaCluster OceSliceUserCache OceSliceReplicaCluster OceSliceSubjectObserver OceSliceILikeIt OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool TalkUtil UtilCxx UtilSlice)

ADD_DC_SERVICE("app/ILikeIt/cache" "ILikeItCache" OceCxxAdapterBuddyByIdReplicaAdapter OceCxxAdapterILikeItCacheAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter ReplicaCluster OceSliceReplicaCluster OceSliceUserCache OceSliceSubjectObserver OceSliceILikeIt OceSliceUserBase OceSliceBuddyByIdCache IceExt OceSliceXceStorm DbCxxPool TalkUtil UtilCxx UtilSlice)

ADD_SERVICE("app/BatchUpdater/src" "BatchUpdaterN" OceCxxAdapterBatchUpdaterUserCountReplicaAdapter OceSliceBatchUpdater ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/GeneralDbCache/src" "GeneralDbCacheN" ReplicaCluster OceSliceGeneralDbCache OceCxxAdapterPresenceAdapter OceSlicePresence OceSliceTalkCommon IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSliceUserCache TalkUtil UtilCxx UtilSlice mysqlpp)

ADD_SERVICE_EXEC("app/GetLocalIP/src" "GetLocalIP" IceExt UtilCxx UtilSlice )

ADD_DC_SERVICE("app/OnlineEventMediator/src" "OnlineEventMediator" OceSliceOnlineEventMediator OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterBuddyByOnlineTimeReplicaAdapter OceCxxAdapterOnlineStateFilterAdapter ReplicaCluster OceSliceUserCache OceSliceBuddyByOnlineTimeCache OceSliceOnlineStateFilter OceSliceUserBase OceSliceReplicaCluster OceSliceSubjectObserver IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/Quest/logic" "QuestLogic" OceCxxAdapterQuestCacheAdapter OceSliceQuest ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)

ADD_SERVICE("app/Quest/cache" "QuestCache" OceSliceQuest ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx util UtilSlice)

ADD_SERVICE("app/MenuCache/replica" "MenuCache" OceCxxAdapterMenuCacheReplicaAdapter ReplicaCluster OceSliceReplicaCluster OceSliceSubjectObserver OceCxxAdapterControllerAdapter OceSlice OceSliceMenuCache OceCxxAdapterFavoriteMenuLogicManagerAdapter OceCxxAdapterRecentMenuLogicManagerAdapter IceExt OceSliceReplicaCluster OceSliceSubjectObserver DbCxxPool OceSliceXceStorm UtilCxx UtilSlice)

ADD_SERVICE("app/TrackSummary/src" "TrackSummaryN" OceCxxAdapterAIGuideCacheAdapter  OceCxxAdapterNotifySenderAdapter OceSliceTrackSummary OceSliceNotifySender ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice )

ADD_SERVICE_EXEC("app/AppClient/ugcviewcount" "UgcViewCount" OceCxxAdapterBuddyByIdReplicaAdapter OceSliceBuddyCommon OceSliceBuddyByIdCache ReplicaCluster IceExt DbCxxPool OceSlice UtilCxx UtilSlice)

ADD_SERVICE("app/ActiveTrackFacade/src" "ActiveTrackFacade" OceCxxAdapterTrackSummaryAdapter OceCxxAdapterQuestCacheAdapter OceCxxAdapterOnlineAdapter OceCxxAdapterUserMonitorAdapter OceCxxAdapterDailyAccessCacheAdapter OceCxxAdapterUserScoreActiveTrackAdapter OceSliceActiveTrack OceSliceTrackSummary OceSliceOnline OceSliceUserMonitor OceSliceQuest OceSliceDailyAccessCache OceSliceUserScoreActiveTrack ReplicaCluster IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice OceSliceQuest )

ADD_SERVICE("app/ActiveMotionFacade/src" "ActiveMotionFacade" OceSliceActiveTrack ReplicaCluster IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice OceSliceQuest )
ADD_SERVICE_EXEC("app/ActiveMotionFacade/test" "ActiveMotionFacadeTest" OceSliceActiveTrack OceCxxAdapterActiveMotionFacadeAdapter ReplicaCluster IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice OceSliceQuest )

ADD_SERVICE("app/AIGuideCache/src" "AIGuideCache" OceCxxAdapterAIGuideCacheAdapter OceSliceAIGuideCache IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice )

