#!/bin/sh

ulimit -s 128
ulimit -n 8192

_CLASSPATH=$CLASSPATH
_CLASSPATH=$CLASSPATH:"/opt/wsep/WEB-INF/classes/"
for i in /opt/wsep/WEB-INF/lib/*.jar
do
    _CLASSPATH=$_CLASSPATH:"$i"
done

for i in /opt/resin/lib/my*.jar
do
    _CLASSPATH=$_CLASSPATH:"$i"
done

#echo $_CLASSPATH
echo ================================================


_CLASSPATH=bin:$_CLASSPATH

/opt/j2sdk/bin/java -Xms256M -Xmx512M -classpath $_CLASSPATH "$@"