<iframe src="/pages/editor/editor.htm?btn=bold,italic,left,center,right,removeformat,link,color,bgcolor,image,face&ver=$revxxx$" frameborder="0" id="rte" class="rte" onload="if(typeof(fnEditorOnLoad) == 'function') {fnEditorOnLoad()}"></iframe>
<script type="text/javascript">
//added by pekkyl for the short cut submit
function quickSendEditorCon() {
	getEl("editorFormBtn").click();
}
</script>
