<script type="text/javascript"><!--
google_ad_client = "pub-3916230650553538";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_ad_type = "text";
google_ad_channel ="";
google_color_border = "d8dfea";
google_color_bg = "f7f7f7";
google_color_link = "3b5998";
google_color_text = "000000";
google_color_url = "3b5998";
//--></script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>