<%@ page pageEncoding="UTF-8" %>
<style type="text/css">
<!--
.regsidebar{ background-color:#f7f7f7; float:left; width:170px; border-top:1px solid #ccc; border-bottom:1px solid #ccc;}
.regsidebar h2{ color:#666; margin:20px 0 20px 20px;}
.regsidebar ul{ margin-left:20px;}
.regsidebar ul li{ margin-bottom:15px; padding-left:22px; line-height:18px; background-position:left 50%; background-repeat:no-repeat;}
.regsidebar ul li.it1{ background-image:url(http://app.xnimg.cn/application/20080708/07/04/L187412264212PUM.jpg);}
.regsidebar ul li.it2{ background-image:url(http://app.xnimg.cn/application/20080627/22/50/L820824663421HEI.jpg);}
.regsidebar ul li.it3{ background-image:url(${applicationScope.urlSmallStatic}/img/newsfeed/blog.gif);}
.regsidebar ul li.it4{ background-image:url(${applicationScope.urlSmallStatic}/img/newsfeed/photo.gif);}
.regsidebar ul li.it5{ background-image:url(${applicationScope.urlSmallStatic}/img/newsfeed/share.gif);}
.regsidebar ul li.it6{ background-image:url(${applicationScope.urlSmallStatic}/img/newsfeed/group.gif);}
.regsidebar ul li.it7{ background-image:url(${applicationScope.urlSmallStatic}/img/newsfeed/film.gif);}
.regsidebar ul li.it8{ background-image:url(${applicationScope.urlSmallStatic}/img/newsfeed/acts.gif);}
.regsidebar ul li.it9{ background-image:url(${applicationScope.urlSmallStatic}/img/newsfeed/forum.gif);}
.regsidebar ul li.it10{ background-image:url(${applicationScope.urlSmallStatic}/img/newsfeed/class.gif);}
-->
</style>
<div class="regsidebar">
	<h2>加入${domainIdentified["siteName"]}你可以:</h2>
	<ul>
		<li class="it1">和朋友抢车位</li>
		<li class="it2">玩好友买卖</li>
		<li class="it3">写日志</li>
		<li class="it4">上传照片</li>
		<li class="it5">分享好东东</li>
		<li class="it6">加入群组</li>
		<li class="it7">评论电影</li>
		<li class="it8">参加活动</li>
		<li class="it9">泡论坛</li>
		<!--li class="it10">寻找班级</li-->
	</ul>
</div>