<%@ page pageEncoding="UTF-8" %>
<%-- make Struts XHTML-compliant --%>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="Description" content="${domainIdentified["siteName"]}是一个真实的社交网络，联络你和你周围的朋友。加入${domainIdentified["siteName"]}你可以:联络朋友，了解他们的最新动态；和朋友分享相片、音乐和电影；找到老同学，结识新朋友；用照片和日志记录生活,展示自我。" />
<meta name="Keywords" content="xiaonei,renren,${domainIdentified["siteName"]},校内,大学,同学,同事,白领,个人主页,博客,相册,群组,社区,交友,聊天,音乐,视频,校园" />
<link href="${applicationScope.urlSmallStatic}/css/base.css?ver=$revxxx$" rel="stylesheet" type="text/css" media="all" />
<link href="${applicationScope.urlSmallStatic}/css/navigationpro.css?ver=$revxxx$" rel="stylesheet" type="text/css" media="all" />
<link href="${applicationScope.urlSmallStatic}/css/super-actions.css?ver=$revxxx$" rel="stylesheet" type="text/css" media="all" />
<link href="${applicationScope.urlSmallStatic}/css/dialogpro.css?ver=$revxxx$" rel="stylesheet" type="text/css">
<link href="${applicationScope.urlSmallStatic}/favicon.ico?ver=2" rel="shortcut icon" type="image/x-icon">
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/util.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/jspro/base.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/prototype.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/xn/base.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/xn/extended.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/xn/string.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/xn/deprecated.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/xn/apps_menu.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/xn/dialogpro.js?ver=$revxxx$"></script>

