#ifndef __Q_CONFIG_CONST_H__
#define __Q_CONFIG_CONST_H__

#include <string>

using namespace std;

namespace segment
{
	const string FWD_PHRASE_FILE_NAME = "FWD_PHRASE_FILE_NAME";
	const string BWD_PHRASE_FILE_NAME = "BWD_PHRASE_FILE_NAME";

	const string ENABLE_NAME_ENTITY_RECOGNITION_NAME = "ENABLE_NAME_ENTITY_RECOGNITION";
	const string ENABLE_ADDRESS_ENTITY_RECOGNITION_NAME = "ENABLE_ADDRESS_ENTITY_RECOGNITION";

	const string SURNAME_ENTITY_FILE_NAME = "SURNAME_ENTITY_FILE_NAME";
	const string DUFIRST_ENTITY_FILE_NAME = "DUFIRST_ENTITY_FILE_NAME";
	const string DUSECOND_ENTITY_FILE_NAME = "DUSECOND_ENTITY_FILE_NAME";
	const string SINNAME_ENTITY_FILE_NAME = "SINNAME_ENTITY_FILE_NAME";

	const string SURNAME_THRESHOLD_NAME = "SURNAME_THRESHOLD";
	const string SINNAME_THRESHOLD_NAME = "SINNAME_THRESHOLD";
	const string DUALNAME_THRESHOLD_NAME = "DUALNAME_THRESHOLD";
	const string NAME_RATIO_NAME = "NAME_RATIO_NAME";

	const string ADDRESS_TRANSFER_FILE_NAME = "ADDRESS_TRANSFER_FILE_NAME";
	
	const string ENABLE_BIDIRECTIONAL_NAME = "ENABLE_BIDIRECTIONAL";
}

#endif
