// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friendcluster.proto

package com.xiaonei.xce.socialgraph.proto;

public final class FriendClusters {
  private FriendClusters() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FriendCluster extends
      com.google.protobuf.GeneratedMessage {
    // Use FriendCluster.newBuilder() to construct.
    private FriendCluster() {
      initFields();
    }
    private FriendCluster(boolean noInit) {}
    
    private static final FriendCluster defaultInstance;
    public static FriendCluster getDefaultInstance() {
      return defaultInstance;
    }
    
    public FriendCluster getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaonei.xce.socialgraph.proto.FriendClusters.internal_static_xce_socialgraph_FriendCluster_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaonei.xce.socialgraph.proto.FriendClusters.internal_static_xce_socialgraph_FriendCluster_fieldAccessorTable;
    }
    
    // optional int32 weight = 1;
    public static final int WEIGHT_FIELD_NUMBER = 1;
    private boolean hasWeight;
    private int weight_ = 0;
    public boolean hasWeight() { return hasWeight; }
    public int getWeight() { return weight_; }
    
    // repeated int32 useridseq = 2;
    public static final int USERIDSEQ_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> useridseq_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getUseridseqList() {
      return useridseq_;
    }
    public int getUseridseqCount() { return useridseq_.size(); }
    public int getUseridseq(int index) {
      return useridseq_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasWeight()) {
        output.writeInt32(1, getWeight());
      }
      for (int element : getUseridseqList()) {
        output.writeInt32(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasWeight()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getWeight());
      }
      {
        int dataSize = 0;
        for (int element : getUseridseqList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getUseridseqList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster result;
      
      // Construct using com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster();
        return builder;
      }
      
      protected com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster.getDescriptor();
      }
      
      public com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster getDefaultInstanceForType() {
        return com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.useridseq_ != java.util.Collections.EMPTY_LIST) {
          result.useridseq_ =
            java.util.Collections.unmodifiableList(result.useridseq_);
        }
        com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster) {
          return mergeFrom((com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster other) {
        if (other == com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster.getDefaultInstance()) return this;
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        if (!other.useridseq_.isEmpty()) {
          if (result.useridseq_.isEmpty()) {
            result.useridseq_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.useridseq_.addAll(other.useridseq_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setWeight(input.readInt32());
              break;
            }
            case 16: {
              addUseridseq(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addUseridseq(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // optional int32 weight = 1;
      public boolean hasWeight() {
        return result.hasWeight();
      }
      public int getWeight() {
        return result.getWeight();
      }
      public Builder setWeight(int value) {
        result.hasWeight = true;
        result.weight_ = value;
        return this;
      }
      public Builder clearWeight() {
        result.hasWeight = false;
        result.weight_ = 0;
        return this;
      }
      
      // repeated int32 useridseq = 2;
      public java.util.List<java.lang.Integer> getUseridseqList() {
        return java.util.Collections.unmodifiableList(result.useridseq_);
      }
      public int getUseridseqCount() {
        return result.getUseridseqCount();
      }
      public int getUseridseq(int index) {
        return result.getUseridseq(index);
      }
      public Builder setUseridseq(int index, int value) {
        result.useridseq_.set(index, value);
        return this;
      }
      public Builder addUseridseq(int value) {
        if (result.useridseq_.isEmpty()) {
          result.useridseq_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.useridseq_.add(value);
        return this;
      }
      public Builder addAllUseridseq(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.useridseq_.isEmpty()) {
          result.useridseq_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.useridseq_);
        return this;
      }
      public Builder clearUseridseq() {
        result.useridseq_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:xce.socialgraph.FriendCluster)
    }
    
    static {
      defaultInstance = new FriendCluster(true);
      com.xiaonei.xce.socialgraph.proto.FriendClusters.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:xce.socialgraph.FriendCluster)
  }
  
  public static final class Person extends
      com.google.protobuf.GeneratedMessage {
    // Use Person.newBuilder() to construct.
    private Person() {
      initFields();
    }
    private Person(boolean noInit) {}
    
    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }
    
    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaonei.xce.socialgraph.proto.FriendClusters.internal_static_xce_socialgraph_Person_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaonei.xce.socialgraph.proto.FriendClusters.internal_static_xce_socialgraph_Person_fieldAccessorTable;
    }
    
    // repeated int32 clusterindexseq = 3;
    public static final int CLUSTERINDEXSEQ_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> clusterindexseq_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getClusterindexseqList() {
      return clusterindexseq_;
    }
    public int getClusterindexseqCount() { return clusterindexseq_.size(); }
    public int getClusterindexseq(int index) {
      return clusterindexseq_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int element : getClusterindexseqList()) {
        output.writeInt32(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getClusterindexseqList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getClusterindexseqList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xiaonei.xce.socialgraph.proto.FriendClusters.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xiaonei.xce.socialgraph.proto.FriendClusters.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.xiaonei.xce.socialgraph.proto.FriendClusters.Person result;
      
      // Construct using com.xiaonei.xce.socialgraph.proto.FriendClusters.Person.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.xiaonei.xce.socialgraph.proto.FriendClusters.Person();
        return builder;
      }
      
      protected com.xiaonei.xce.socialgraph.proto.FriendClusters.Person internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.xiaonei.xce.socialgraph.proto.FriendClusters.Person();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaonei.xce.socialgraph.proto.FriendClusters.Person.getDescriptor();
      }
      
      public com.xiaonei.xce.socialgraph.proto.FriendClusters.Person getDefaultInstanceForType() {
        return com.xiaonei.xce.socialgraph.proto.FriendClusters.Person.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.xiaonei.xce.socialgraph.proto.FriendClusters.Person build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.xiaonei.xce.socialgraph.proto.FriendClusters.Person buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.xiaonei.xce.socialgraph.proto.FriendClusters.Person buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.clusterindexseq_ != java.util.Collections.EMPTY_LIST) {
          result.clusterindexseq_ =
            java.util.Collections.unmodifiableList(result.clusterindexseq_);
        }
        com.xiaonei.xce.socialgraph.proto.FriendClusters.Person returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaonei.xce.socialgraph.proto.FriendClusters.Person) {
          return mergeFrom((com.xiaonei.xce.socialgraph.proto.FriendClusters.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xiaonei.xce.socialgraph.proto.FriendClusters.Person other) {
        if (other == com.xiaonei.xce.socialgraph.proto.FriendClusters.Person.getDefaultInstance()) return this;
        if (!other.clusterindexseq_.isEmpty()) {
          if (result.clusterindexseq_.isEmpty()) {
            result.clusterindexseq_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.clusterindexseq_.addAll(other.clusterindexseq_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 24: {
              addClusterindexseq(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addClusterindexseq(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated int32 clusterindexseq = 3;
      public java.util.List<java.lang.Integer> getClusterindexseqList() {
        return java.util.Collections.unmodifiableList(result.clusterindexseq_);
      }
      public int getClusterindexseqCount() {
        return result.getClusterindexseqCount();
      }
      public int getClusterindexseq(int index) {
        return result.getClusterindexseq(index);
      }
      public Builder setClusterindexseq(int index, int value) {
        result.clusterindexseq_.set(index, value);
        return this;
      }
      public Builder addClusterindexseq(int value) {
        if (result.clusterindexseq_.isEmpty()) {
          result.clusterindexseq_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.clusterindexseq_.add(value);
        return this;
      }
      public Builder addAllClusterindexseq(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.clusterindexseq_.isEmpty()) {
          result.clusterindexseq_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.clusterindexseq_);
        return this;
      }
      public Builder clearClusterindexseq() {
        result.clusterindexseq_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:xce.socialgraph.Person)
    }
    
    static {
      defaultInstance = new Person(true);
      com.xiaonei.xce.socialgraph.proto.FriendClusters.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:xce.socialgraph.Person)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xce_socialgraph_FriendCluster_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xce_socialgraph_FriendCluster_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xce_socialgraph_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xce_socialgraph_Person_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023friendcluster.proto\022\017xce.socialgraph\"2" +
      "\n\rFriendCluster\022\016\n\006weight\030\001 \001(\005\022\021\n\tuseri" +
      "dseq\030\002 \003(\005\"!\n\006Person\022\027\n\017clusterindexseq\030" +
      "\003 \003(\005B3\n!com.xiaonei.xce.socialgraph.pro" +
      "toB\016FriendClusters"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_xce_socialgraph_FriendCluster_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_xce_socialgraph_FriendCluster_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xce_socialgraph_FriendCluster_descriptor,
              new java.lang.String[] { "Weight", "Useridseq", },
              com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster.class,
              com.xiaonei.xce.socialgraph.proto.FriendClusters.FriendCluster.Builder.class);
          internal_static_xce_socialgraph_Person_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_xce_socialgraph_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xce_socialgraph_Person_descriptor,
              new java.lang.String[] { "Clusterindexseq", },
              com.xiaonei.xce.socialgraph.proto.FriendClusters.Person.class,
              com.xiaonei.xce.socialgraph.proto.FriendClusters.Person.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
