MACRO ( PROCESS_ADDITIONAL_SRC_DIR libraryname ARGN_ARGUMENT ) 
  FOREACH(directory ${ARGN_ARGUMENT})
    IF(${directory} MATCHES "ADDITIONAL_SOURCE_DIR")
      STRING(LENGTH ${directory} temp_len)
      MATH(EXPR temp_len ${temp_len}-22)
      STRING(SUBSTRING ${directory} 22 ${temp_len} temp_src_directory)
      AUX_SOURCE_DIRECTORY("${XNS_ROOT_DIR}/${temp_src_directory}" TEMP_${libraryname}_SRC_CPP_SOURCE )
      FOREACH(temp_src_file ${TEMP_${libraryname}_SRC_CPP_SOURCE})
        LIST(APPEND BUILD_${libraryname}_SRC_CPP_SOURCE ${temp_src_file})
      ENDFOREACH(temp_src_file)
    ELSE (${directory} MATCHES "ADDITIONAL_SOURCE_DIR")
      LIST(APPEND FILTERED_${libraryname}_ARGN ${directory})
    ENDIF(${directory} MATCHES "ADDITIONAL_SOURCE_DIR")
  ENDFOREACH(directory) 
ENDMACRO ( PROCESS_ADDITIONAL_SRC_DIR )

MACRO ( ADD_ADDITIONAL_DC_SERVICE directoryname libraryname )
	MESSAGE(STATUS "DEBUG: ${ARGN}")
	AUX_SOURCE_DIRECTORY("${XNS_ROOT_DIR}/${directoryname}" BUILD_${libraryname}_SRC_CPP_SOURCE )
  PROCESS_ADDITIONAL_SRC_DIR(${libraryname} "${ARGN}")
  ADD_LIBRARY( ${libraryname} SHARED EXCLUDE_FROM_ALL ${BUILD_${libraryname}_SRC_CPP_SOURCE})
	TARGET_LINK_LIBRARIES( ${libraryname} ${FILTERED_${libraryname}_ARGN} rdc-client.a libmemcached.so libprotobuf.a libzookeeper_mt.a libactivemq-cpp.a libapr-1.a libaprutil-1.so)
ENDMACRO ( ADD_ADDITIONAL_DC_SERVICE )

MACRO ( ADD_ADDITIONAL_DC_SERVICE_EXEC directoryname libraryname )
	MESSAGE(STATUS "DEBUG: ${ARGN}")
	AUX_SOURCE_DIRECTORY("${XNS_ROOT_DIR}/${directoryname}" BUILD_${libraryname}_SRC_CPP_SOURCE )
  PROCESS_ADDITIONAL_SRC_DIR(${libraryname} "${ARGN}")
  ADD_EXECUTABLE( ${libraryname} EXCLUDE_FROM_ALL ${BUILD_${libraryname}_SRC_CPP_SOURCE})
	TARGET_LINK_LIBRARIES( ${libraryname} ${FILTERED_${libraryname}_ARGN} rdc-client.a libmemcached.so libprotobuf.a libzookeeper_mt.a libactivemq-cpp.a libapr-1.a libaprutil-1.so)
ENDMACRO ( ADD_ADDITIONAL_DC_SERVICE_EXEC )

MACRO ( ADD_ADDITIONAL_SERVICE directoryname libraryname )
	MESSAGE(STATUS "DEBUG: ${ARGN}")
	AUX_SOURCE_DIRECTORY("${XNS_ROOT_DIR}/${directoryname}" BUILD_${libraryname}_SRC_CPP_SOURCE )	
  PROCESS_ADDITIONAL_SRC_DIR(${libraryname} "${ARGN}")
  ADD_LIBRARY( ${libraryname} SHARED EXCLUDE_FROM_ALL ${BUILD_${libraryname}_SRC_CPP_SOURCE})
	TARGET_LINK_LIBRARIES( ${libraryname} ${FILTERED_${libraryname}_ARGN} )
ENDMACRO ( ADD_ADDITIONAL_SERVICE )

MACRO ( ADD_ADDITIONAL_SERVICE_EXEC directoryname libraryname )
	MESSAGE(STATUS "DEBUG: ${ARGN}")
	AUX_SOURCE_DIRECTORY("${XNS_ROOT_DIR}/${directoryname}" BUILD_${libraryname}_SRC_CPP_SOURCE )
  PROCESS_ADDITIONAL_SRC_DIR(${libraryname} "${ARGN}")
  ADD_EXECUTABLE( ${libraryname} EXCLUDE_FROM_ALL ${BUILD_${libraryname}_SRC_CPP_SOURCE})
	TARGET_LINK_LIBRARIES( ${libraryname} ${FILTERED_${libraryname}_ARGN} )
ENDMACRO ( ADD_ADDITIONAL_SERVICE_EXEC )
