INCLUDE_DIRECTORIES(/data/home/yuwei.mu/xce/include)
LINK_DIRECTORIES(/data/home/yuwei.mu/xce/lib)
INCLUDE_DIRECTORIES(/data/home/yuwei.mu/xce/include/ClearSilver)

ADD_COMPONENT("Notify/util" "NotifyUtil" OceCxxAdapterIdCacheReaderAdapter OceSliceIdCache OceSliceTicket OceCxxAdapterTicketAdapter neo_cgi neo_cs neo_utl)

#ADD_COMPONENT("Notify/loader" "NotifyLoader" OceCxxAdapterTicketAdapter DbCxxPool UtilCxx FeedMemcClient NotifyUtil)
# use NotifyContentAdapter
#ADD_SERVICE("Notify/index" "NotifyIndex" OceCxxAdapterNotifyStormAdapter OceSliceNotifyStorm OceSliceNotify FeedMemcClient NotifyUtil OceCxxAdapterIqMsgHandlerAdapter OceSliceUserBase OceSliceTalkLogic OceSliceTalkCache OceSliceTalkCommon OceCxxAdapterNotifyContentAdapter ReplicaCluster IceExt  OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx UtilSlice ctemplate breakpad ) 

# for memcached 
ADD_SERVICE("Notify/index" "NotifyIndex" OceCxxAdapterMucOnlineCenterAdapter OceCxxAdapterTalkFunStateAdapter OceCxxAdapterNotifyStormAdapter OceCxxAdapterNotifyContentLoaderAdapter OceSliceNotifyStorm OceSliceNotify NotifyUtil OceCxxAdapterIqMsgHandlerAdapter OceSliceUserBase OceSliceTalkLogic OceSliceTalkCache OceSliceTalkCommon OceCxxAdapterNotifyContentAdapter ReplicaCluster IceExt  OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx TalkUtil OceSlice UtilSlice ctemplate breakpad ) 

ADD_SERVICE("Notify/index_n" "NotifyIndexN" OceCxxAdapterMucOnlineCenterAdapter OceCxxAdapterTalkFunStateAdapter OceCxxAdapterNotifyStormAdapter OceSliceNotifyStorm OceSliceNotify NotifyUtil OceCxxAdapterIqMsgHandlerAdapter OceSliceUserBase OceSliceTalkLogic OceSliceTalkCache OceSliceTalkCommon OceCxxAdapterNotifyContentAdapter OceCxxAdapterNotifyContentLoaderAdapter ReplicaCluster IceExt  OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice TalkUtil UtilCxx UtilSlice ctemplate breakpad)

ADD_SERVICE("Notify/content" "NotifyContent" OceCxxAdapterMucOnlineCenterAdapter OceCxxAdapterTalkFunStateAdapter OceSliceNotify ReplicaCluster IceExt  OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice TalkUtil UtilCxx UtilSlice FeedMemcClient )

ADD_SERVICE("Notify/loader" "NotifyContentLoader" OceCxxAdapterMucOnlineCenterAdapter OceCxxAdapterTalkFunStateAdapter NotifyUtil OceSliceNotify FeedMemcClient OceSliceRFeed OceSliceFeedMemcProxy ReplicaCluster IceExt OceSliceReplicaCluster OceCxxAdapterNotifyContentLoaderAdapter OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice TalkUtil IceExt UtilCxx UtilSlice)

ADD_SERVICE("Notify/dispatcher_n" "NotifyDispatcherN" OceCxxAdapterMucOnlineCenterAdapter OceCxxAdapterTalkFunStateAdapter NotifyUtil OceCxxAdapterFeedGroupAdapter OceCxxAdapterUserPassportAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterNotifyDispatcherAdapter OceCxxAdapterNotifyIndexAdapter OceCxxAdapterNotifyIndexNAdapter OceCxxAdapterNotifyContentAdapter OceCxxAdapterNotifyContentLoaderAdapter OceCxxAdapterFeedContentAdapter ReplicaCluster IceExt OceSliceSubjectObserver OceSliceUserBase OceSliceReplicaCluster OceSliceRFeed OceSliceUserCache OceSliceNotify OceSliceXceStorm DbCxxPool OceProto UtilCxx OceSlice TalkUtil UtilSlice TalkUtil ctemplate)

ADD_SERVICE("Notify/dispatcher" "NotifyDispatcher"  OceCxxAdapterMucOnlineCenterAdapter OceCxxAdapterTalkFunStateAdapter NotifyUtil OceSliceUserBase OceSliceNotify OceCxxAdapterUserPassportAdapter OceCxxAdapterNotifyDispatcherNAdapter OceCxxAdapterNotifyContentLoaderAdapter ReplicaCluster IceExt  OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx TalkUtil UtilSlice OceSlice ctemplate breakpad)

#ADD_SERVICE("talk/WTransit/src" "WTransit" OceCxxAdapterTalkFunStateAdapter OceCxxAdapterIMStormAdapter OceCxxAdapterMucOnlineCenterAdapter OceSliceSubjectObserver IceExt  OceSliceXceStorm DbCxxPool FeedMemcClient OceSlice UtilCxx UtilSlice breakpad TalkUtil)

#ADD_SERVICE("Notify/gate" "NotifyGate" NotifyUtil OceSliceWTransit OceSliceNotify OceCxxAdapterFeedNewsAdapter OceCxxAdapterFeedItemAdapter OceCxxAdapterWTransitAdapter OceCxxAdapterAPNSNotifyAdapter OceCxxAdapterNotifyIndexAdapter ReplicaCluster IceExt  OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm OceSliceAPNSNotify OceSliceRFeed OceSliceTalkCommon DbCxxPool UtilCxx UtilSlice fcgi ctemplate breakpad)

ADD_SERVICE("Notify/gate" "NotifyGate" OceCxxAdapterMucOnlineCenterAdapter OceCxxAdapterTalkFunStateAdapter NotifyUtil OceSliceWTransit OceSliceNotify OceSliceNotifyStorm OceCxxAdapterNotifyIndexNAdapter OceCxxAdapterNotifyContentLoaderAdapter OceCxxAdapterNotifyContentAdapter OceCxxAdapterWTransitAdapter OceCxxAdapterIdCacheReaderAdapter OceSliceIdCache OceCxxAdapterAPNSNotifyAdapter OceCxxAdapterNotifyStormAdapter OceCxxAdapterNotifyIndexAdapter ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm OceSliceAPNSNotify OceSliceRFeed OceSliceTalkCommon DbCxxPool OceSlice TalkUtil UtilCxx UtilSlice fcgi ctemplate breakpad)

ADD_SERVICE("Notify/redirection" "Redirection" NotifyUtil OceSliceNotify OceSliceRedirection OceCxxAdapterTransferManagerAdapter OceCxxAdapterTalkProxyAdapter  ReplicaCluster IceExt  OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm  OceSlice DbCxxPool UtilCxx UtilSlice fcgi ctemplate)

ADD_SERVICE("Notify/feed_gate" "FeedGate" NotifyUtil OceCxxAdapterFeedViewAdapter OceSliceFeedView OceCxxAdapterTimeLineFeedReplicaAdapter OceSliceTimeLineFeed OceSliceNotify OceSliceRFeed OceCxxAdapterFeedContentAdapter OceCxxAdapterFeedGroupAdapter OceCxxAdapterFeedAssistantNAdapter OceCxxAdapterFeedContentAdapter OceSliceIdCache OceCxxAdapterIdCacheReaderAdapter FeedMemcClient ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx UtilSlice TalkUtil fcgi ctemplate boost_regex)

#ADD_SERVICE("Notify/cs_feed_gate" "FeedGateCS" NotifyUtil OceSliceNotify OceSliceRFeed OceCxxAdapterFeedContentAdapter OceCxxAdapterFeedGroupAdapter OceCxxAdapterFeedAssistantNAdapter OceCxxAdapterFeedContentAdapter FeedMemcClient ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx UtilSlice TalkUtil fcgi ctemplate boost_regex)

ADD_SERVICE("Notify/admin" "NotifyAdmin" NotifyUtil OceSliceNotify OceSliceRmessageGate OceCxxAdapterNotifyIndexAdapter OceCxxAdapterNotifyIndexNAdapter OceCxxAdapterNotifyContentLoaderAdapter OceCxxAdapterNotifyContentAdapter OceCxxAdapterRmessageGateAdapter OceCxxAdapterNotifyGateAdapter OceCxxAdapterNotifyDispatcherNAdapter ReplicaCluster IceExt  OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx UtilSlice fcgi ctemplate)

ADD_SERVICE("Notify/notepad" "TalkNotepad" NotifyUtil OceSliceTicket OceCxxAdapterTicketAdapter OceSliceTalkNotepad ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceTalkCommon OceSliceXceStorm DbCxxPool UtilCxx UtilSlice fcgi ctemplate)

ADD_SERVICE("Notify/storm" "NotifyStorm" IceExt ReplicaCluster OceSliceReplicaCluster OceSliceSubjectObserver OceSliceNotifyStorm OceSliceXceStorm DbCxxPool UtilCxx UtilSlice mysqlpp)

ADD_SERVICE("Notify/rmessage_gate" "RmessageGate" NotifyUtil OceSliceWTransit OceSliceNotify OceCxxAdapterRmessageGateAdapter OceSliceRmessageGate OceCxxAdapterNotifyIndexNAdapter OceCxxAdapterFeedNewsAdapter OceCxxAdapterWTransitAdapter OceCxxAdapterAPNSNotifyAdapter OceCxxAdapterNotifyIndexAdapter OceSliceIdCache OceCxxAdapterIdCacheReaderAdapter ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm OceSliceAPNSNotify OceSliceRFeed DbCxxPool UtilCxx UtilSlice fcgi ctemplate OceSlice OceCxxAdapterNotifyGateAdapter OceCxxAdapterNotifyContentLoaderAdapter OceCxxAdapterNotifyContentAdapter boost_regex breakpad)

#ADD_SERVICE("Notify/test" "HelloWorld" OceSliceHelloWorld IceExt ReplicaCluster OceSliceReplicaCluster OceSliceSubjectObserver OceSliceNotifyStorm OceSliceXceStorm DbCxxPool UtilCxx UtilSlice mysqlpp)

