ADD_SERVICE("app/FootprintUnite/FootprintFacade" "FootprintFacade" OceCxxAdapterMonitorAdapter OceCxxAdapterLoveFootprintByInterviewerAdapter OceCxxAdapterLoveFootprintByIntervieweeAdapter OceCxxAdapterVisitFootprintAdapter OceCxxAdapterHomeFootprintAdapter OceCxxAdapterFootprintFacadeAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceBatchUpdater OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)

ADD_DC_SERVICE("app/FootprintUnite/HomeFootprint" "HomeFootprint" OceCxxAdapterHomeFootprintReplicaAdapter OceCxxAdapterMonitorAdapter OceCxxAdapterFootprintViewAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice OceProto)

ADD_SERVICE("app/FootprintUnite/Preloader/HomeFootprintPreloader/HomeFootprintReaderPreloader" "HomeFootprintReaderPreloader" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/Preloader/HomeFootprintPreloader/HomeFootprintBufReaderPreloader" "HomeFootprintBufReaderPreloader" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/Preloader/HomeFootprintPreloader/HomeUserVisitCountReaderPreloader" "HomeUserVisitCountReaderPreloader" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/Preloader/HomeFootprintReplicaPreloader/HomeFootprintReplicaReaderPreloader" "HomeFootprintReplicaReaderPreloader" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/Preloader/HomeFootprintReplicaPreloader/HomeFootprintBufReplicaReaderPreloader" "HomeFootprintBufReplicaReaderPreloader" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/Preloader/HomeFootprintReplicaPreloader/HomeUserVisitCountReplicaReaderPreloader" "HomeUserVisitCountReplicaReaderPreloader" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/HomeFootprintReplica" "HomeFootprintReplica" OceCxxAdapterHomeFootprintAdapter OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

#ADD_SERVICE_EXEC("app/FootprintUnite/HomeFootprint" "HomeFootprintMerge" OceCxxAdapterHomeFootprintAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater  OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

#ADD_SERVICE_EXEC("app/FootprintUnite/FootprintWarmer/src" "FootprintWarmer" OceCxxAdapterHomeFootprintAdapter OceCxxAdapterVisitFootprintAdapter OceCxxAdapterFootprintFacadeAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater  OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/FootprintView/src" "FootprintView" OceCxxAdapterHomeFootprintAdapter OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintView OceSliceFootprintUnite OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceBatchUpdater OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/UgcFootprint" "VisitFootprint" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintUnite/CommonFootprint" "LoveFootprint" ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

#ADD_SERVICE("app/FootprintFilter/src" "FootprintFilterN" OceSliceFootprint OceSliceFootprintNew OceSliceFootprintFilter OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater ReplicaCluster IceExt  OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/FootprintUgc/src" "BlogFootprintL" OceCxxAdapterMonitorAdapter ReplicaCluster OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceFootprint OceSliceFootprintNew OceSliceFootprintFilter OceSliceUser OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice)
#ADD_SERVICE_EXEC("app/FootprintUgc/src" "BlogFootprintFlushDB" OceCxxAdapterMonitorAdapter ReplicaCluster OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceFootprint OceSliceFootprintNew OceSliceFootprintFilter OceSliceUser OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FootprintNew/src" "AppFootprint" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFootprintNew OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice)

ADD_DC_SERVICE("app/MiniGroup/MiniGroupPreloader/src" "MiniGroupPreloader" MiniGroupCommon OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceMiniGroup OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice OceProto)

ADD_COMPONENT("app/MiniGroup/MiniGroupCommon/src" "MiniGroupCommon" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceMiniGroup OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter OceProto IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice )

ADD_DC_SERVICE("app/MiniGroup/MiniGroupManager/src" "MiniGroupManager" OceCxxAdapterMiniGroupWriterAdapter OceCxxAdapterMonitorAdapter MiniGroupCommon ReplicaCluster OceSliceMiniGroup OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice OceProto)

ADD_DC_SERVICE("app/MiniGroup/User2MiniGroupPreloader/src" "User2MiniGroupPreloader" MiniGroupCommon OceCxxAdapterMiniGroupManagerAdapter OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceMiniGroup OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice OceProto)

ADD_DC_SERVICE("app/MiniGroup/MiniGroupWriter/src" "MiniGroupWriter" OceCxxAdapterMiniGroupManagerAdapter MiniGroupCommon OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceMiniGroup OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice OceProto)

ADD_DC_SERVICE("app/DBWriter/src" "DBWriter" OceSliceTripodProducerManager OceCxxAdapterMonitorAdapter TripodClient TripodInternalClient TripodConfigClient TripodConfigUtil ReplicaCluster OceSliceTripodCacheManager OceSliceTripodProducerManager OceSliceTripodData OceSliceTripodException OceSliceDBManager OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice Base Redisc OceProto)

ADD_DC_SERVICE_EXEC("app/DBWriter/zkadmin" "ZKAdmin" OceSliceTripodProducerManager OceCxxAdapterMonitorAdapter TripodClient TripodInternalClient TripodConfigClient TripodConfigUtil ReplicaCluster OceSliceTripodCacheManager OceSliceTripodProducerManager OceSliceTripodData OceSliceTripodException OceSliceDBManager OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice Base Redisc OceProto)

ADD_DC_SERVICE_EXEC("app/DBWriter/test" "DBWriterTest" OceSliceTripodProducerManager OceCxxAdapterDBWriterAdapter OceCxxAdapterMonitorAdapter TripodClient TripodInternalClient TripodConfigClient TripodConfigUtil ReplicaCluster OceSliceTripodCacheManager OceSliceTripodProducerManager OceSliceTripodData OceSliceTripodException OceSliceDBManager OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice Base Redisc OceProto)

ADD_SERVICE("app/FriendsRecentPhotos/FriendsRecentPhotosManager/src" "FriendsRecentPhotosManager" OceCxxAdapterBuddyByIdReplicaAdapter OceCxxAdapterFriendsRecentPhotosWriterAdapter OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFriendsRecentPhotos OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FriendsRecentPhotos/FriendsRecentPhotosWriter/src" "FriendsRecentPhotosWriter" OceCxxAdapterFriendsRecentPhotosManagerAdapter OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFriendsRecentPhotos OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/FriendsRecentPhotos/FriendsRecentPhotosPreloader/src" "FriendsRecentPhotosPreloader" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceFriendsRecentPhotos OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx OceSlice UtilSlice)

ADD_SERVICE_EXEC("app/FriendsRecentPhotos/tools/src" "FriendsPhotosDBOperator" OceSliceFriendsRecentPhotos OceCxxAdapterActiveTrackAdapter OceCxxAdapterMonitorAdapter   OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater  OceCxxAdapterMonitorAdapter OceSliceMonitor OceCxxAdapterBuddyCoreAdapter OceCxxAdapterBuddyByIdReplicaAdapter ReplicaCluster OceSliceXceStorm OceSliceReplicaCluster OceSliceSubjectObserver DbCxxPool IceExt UtilCxx OceSlice UtilSlice)

ADD_SERVICE("app/RecentContact/src" "RecentContact" OceCxxAdapterMonitorAdapter ReplicaCluster OceSliceRecentContact OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceUser OceSliceMonitor OceCxxAdapterActiveTrackAdapter IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/Bulletin/admin" "BulletinAdmin" OceCxxAdapterBulletinAdapter OceSliceBulletin ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)
    
ADD_DC_SERVICE("app/Bulletin/manager" "BulletinManager" OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterUserBornAdapter OceCxxAdapterUserStageAdapter OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceCxxAdapterUserDescAdapter OceCxxAdapterUserDescReaderAdapter OceCxxAdapterUserNetworkAdapter OceCxxAdapterUserNetworkReaderAdapter OceCxxAdapterUserNetworkWriterAdapter OceSliceActiveTrack OceSliceXceLogger OceSliceUserCache OceSliceUserBase OceSliceUserDesc OceSliceUserNetwork OceSliceBulletin ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice OceProto)

ADD_SERVICE("app/Tips/admin" "TipsAdmin" OceCxxAdapterTipsAdapter OceSliceTips ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)
    
ADD_DC_SERVICE("app/Tips/manager" "TipsManager" OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterUserBornAdapter OceCxxAdapterUserStageAdapter OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceCxxAdapterUserDescAdapter OceCxxAdapterUserDescReaderAdapter OceCxxAdapterUserNetworkAdapter OceCxxAdapterUserNetworkReaderAdapter OceCxxAdapterUserNetworkWriterAdapter OceSliceActiveTrack OceSliceXceLogger OceSliceUserCache OceSliceUserBase OceSliceUserDesc OceSliceUserNetwork OceSliceTips ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice OceProto)

ADD_DC_SERVICE("app/ILikeIt/logic" "ILikeItLogic" OceCxxAdapterILikeItCacheAdapter OceCxxAdapterILikeItLogicAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter ReplicaCluster OceSliceReplicaCluster OceSliceSubjectObserver OceSliceDataSync OceSliceILikeIt OceSliceUserBase OceSliceNotify OceSliceUserCache OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool TalkUtil UtilCxx UtilSlice OceProto)

ADD_DC_SERVICE("app/ILikeIt/cache" "ILikeItCache" OceCxxAdapterBuddyByIdReplicaAdapter OceCxxAdapterILikeItCacheAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter ReplicaCluster OceSliceReplicaCluster OceSliceUserCache OceSliceSubjectObserver OceSliceILikeIt OceSliceUserBase OceSliceBuddyByIdCache OceSliceNotify OceSliceDataSync IceExt OceSliceXceStorm DbCxxPool TalkUtil UtilCxx UtilSlice OceProto)

ADD_DC_SERVICE("app/ILikeIt/tripodcache" "TripodLikeCache" OceSliceTripodProducerManager OceCxxAdapterBuddyByIdReplicaAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter TripodClient TripodInternalClient TripodConfigClient TripodConfigUtil ReplicaCluster OceSliceTripodCacheManager OceSliceTripodProducerManager OceSliceTripodData OceSliceTripodException OceSliceReplicaCluster OceSliceUserCache OceSliceSubjectObserver OceSliceILikeIt OceSliceUserBase OceSliceBuddyByIdCache OceSliceNotify IceExt OceSliceXceStorm DbCxxPool TalkUtil UtilCxx UtilSlice Base Redisc OceProto)

ADD_DC_SERVICE("app/ILikeIt/preloader/cpp" "ILikeItPreloader" OceCxxAdapterBuddyByIdReplicaAdapter OceCxxAdapterILikeItCacheAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter ReplicaCluster OceSliceReplicaCluster OceSliceUserCache OceSliceSubjectObserver OceSliceILikeIt OceSliceUserBase OceSliceBuddyByIdCache OceSliceNotify IceExt OceSliceXceStorm DbCxxPool TalkUtil UtilCxx UtilSlice OceProto)

ADD_SERVICE("app/BatchUpdater/src" "BatchUpdaterN" OceCxxAdapterMonitorAdapter OceCxxAdapterBatchUpdaterUserCountReplicaAdapter OceSliceBatchUpdater ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceMonitor  OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/GeneralDbCache/src" "GeneralDbCacheN" ReplicaCluster OceSliceGeneralDbCache OceCxxAdapterPresenceAdapter OceSlicePresence OceSliceTalkCommon IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSliceUserCache TalkUtil UtilCxx UtilSlice mysqlpp)

ADD_SERVICE_EXEC("app/GetLocalIP/src" "GetLocalIP" IceExt UtilCxx UtilSlice )

ADD_DC_SERVICE("app/OnlineEventMediator/src" "OnlineEventMediator" OceSliceOnlineEventMediator OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterUserCacheAdapter OceCxxAdapterDistUserCacheReloaderAdapter OceCxxAdapterBuddyByOnlineTimeReplicaAdapter OceCxxAdapterOnlineStateFilterAdapter ReplicaCluster OceSliceUserCache OceSliceBuddyByOnlineTimeCache OceSliceOnlineStateFilter OceSliceUserBase OceSliceReplicaCluster OceSliceSubjectObserver IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice)

ADD_SERVICE("app/Quest/logic" "QuestLogic" OceCxxAdapterQuestCacheAdapter OceSliceQuest ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice)

ADD_SERVICE("app/Quest/cache" "QuestCache" OceSliceQuest ReplicaCluster IceExt OceSliceReplicaCluster OceSliceSubjectObserver OceSliceXceStorm DbCxxPool UtilCxx util UtilSlice)

ADD_DC_SERVICE("app/MenuCache/replica" "MenuCache" OceCxxAdapterMenuCacheReplicaAdapter ReplicaCluster OceSliceReplicaCluster OceSliceSubjectObserver OceCxxAdapterControllerAdapter OceSlice OceSliceMenuCache OceCxxAdapterFavoriteMenuLogicManagerAdapter OceCxxAdapterRecentMenuLogicManagerAdapter IceExt OceSliceReplicaCluster OceSliceSubjectObserver DbCxxPool OceSliceXceStorm UtilCxx UtilSlice OceProto)

ADD_DC_SERVICE("app/MenuCache/MenuTripod" "MenuCacheTripod" OceSliceTripodProducerManager ReplicaCluster OceSliceReplicaCluster OceSliceSubjectObserver TripodClient TripodInternalClient TripodConfigClient TripodConfigUtil OceCxxAdapterControllerAdapter OceSlice OceSliceMenuCache IceExt OceSliceReplicaCluster OceSliceSubjectObserver DbCxxPool OceSliceXceStorm UtilCxx UtilSlice Base Redisc OceProto)

ADD_ADDITIONAL_DC_SERVICE_EXEC("app/MenuCache/test" "MenuDBOperator" "ADDITIONAL_SOURCE_DIR_app/MenuCache/MenuTripod" OceSliceTripodProducerManager ReplicaCluster OceSliceReplicaCluster OceSliceSubjectObserver TripodClient TripodInternalClient TripodConfigClient TripodConfigUtil OceCxxAdapterControllerAdapter OceSlice OceSliceMenuCache IceExt OceSliceReplicaCluster OceSliceSubjectObserver DbCxxPool OceSliceXceStorm UtilCxx UtilSlice Base Redisc OceProto)

ADD_SERVICE_EXEC("app/AppClient/ugcviewcount" "UgcViewCount" OceCxxAdapterBuddyByIdReplicaAdapter OceSliceBuddyCommon OceSliceBuddyByIdCache ReplicaCluster IceExt DbCxxPool OceSlice UtilCxx UtilSlice)

ADD_SERVICE("app/ActiveTrackFacade/src" "ActiveTrackFacade" OceCxxAdapterOnlineAdapter OceCxxAdapterUserMonitorAdapter OceCxxAdapterDailyAccessCacheAdapter OceCxxAdapterUserScoreActiveTrackAdapter OceSliceActiveTrack OceSliceOnline OceSliceUserMonitor OceSliceDailyAccessCache OceSliceUserScoreActiveTrack ReplicaCluster IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice )

ADD_SERVICE("app/ActiveMotionFacade/src" "ActiveMotionFacade" OceSliceActiveTrack ReplicaCluster IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice )
ADD_SERVICE_EXEC("app/ActiveMotionFacade/test" "ActiveMotionFacadeTest" OceSliceActiveTrack OceCxxAdapterActiveMotionFacadeAdapter ReplicaCluster IceExt OceSliceXceStorm DbCxxPool UtilCxx UtilSlice )

ADD_SERVICE("app/AIGuideCache/src" "AIGuideCache" OceCxxAdapterAIGuideCacheAdapter OceSliceAIGuideCache IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx UtilSlice )

ADD_SERVICE_EXEC("app/FootprintUnite/tools" "FootprintTool" OceCxxAdapterHomeFootprintReplicaAdapter OceCxxAdapterMonitorAdapter OceCxxAdapterFootprintViewAdapter ReplicaCluster OceSliceFootprintUnite OceCxxAdapterBatchUpdaterAdapter OceSliceBatchUpdater OceSliceFootprintView OceSliceUser OceCxxAdapterActiveTrackAdapter OceCxxAdapterActiveTrackFacadeAdapter OceSliceActiveTrack IceExt OceSliceXceStorm DbCxxPool OceSlice UtilCxx OceSlice UtilSlice OceProto)
