
FILE( GLOB BUILD_TRIPODINTERNALCLIENT_SRC_CPP_SOURCE "${XNS_ROOT_DIR}/tripod-new/src/cpp/internalclient/*.cpp" )

GENERATE_ARCHIVE_EACH( TripodInternalClient "${BUILD_TRIPODINTERNALCLIENT_SRC_CPP_SOURCE}")
