{
	'includes' : [
		'socialgraph_common.gyp',
	],
  'variables': {
   'PROTOC_PATH':'/usr/local/distcache-dev/bin/protoc',
   'MAKE_TPL_VARNAMES_PATH':'/usr/local/xce-dev/bin/make_tpl_varnames_h',
   'ICE_PATH':'<!(echo $ICE_HOME)',
   'SLICE2CPP_PATH':'<(ICE_PATH)/bin/slice2cpp',
   'BOOST_PATH':'/usr/local/xce',
  },
	'target_defaults' : {
		'target_defaults': {
      'cflags':['-fPIC', '-O2'],
		},
		'include_dirs' : [
			'<(main_project_path)/third-party/include/',
			'<(main_project_path)/third-party/redis-c-driver',
		],
		'link_settings' : {
			'libraries' : [
				'-L /opt/jsoncpp-src-0.5.0/libs/linux-gcc-4.1.2',
				'-ljson_linux-gcc-4.1.2_libmt',
			],
			'ldflags' : [
			],
		},
		'dependencies' : [
			'../3rdparty.gyp:hiredis',
			'../base.gyp:base',
			'../xce_base.gyp:xce_base',
			'../tripod2.gyp:tripod_core',
		],
	},
	'targets' : [
		{
			'target_name' : 'RecommendationExperimentI',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentI/recommendationexperimentI.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentI/recommendationexperimentI.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentII',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentII/recommendationexperimentII.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentII/recommendationexperimentII.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentIII',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentIII/recommendationexperimentIII.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentIII/recommendationexperimentIII.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentIV',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentIV/recommendationexperimentIV.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentIV/recommendationexperimentIV.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentV',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentV/recommendationexperimentV.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentV/recommendationexperimentV.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentVI',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVI/recommendationexperimentVI.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVI/recommendationexperimentVI.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentVII',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVII/recommendationexperimentVII.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVII/recommendationexperimentVII.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentVIII',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVIII/recommendationexperimentVIII.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVIII/recommendationexperimentVIII.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentVIIII',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVIIII/recommendationexperimentVIIII.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVIIII/recommendationexperimentVIIII.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationExperimentVV',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVV/recommendationexperimentVV.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/experimentVV/recommendationexperimentVV.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'RecommendationOnline',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/home/online/recommendationonlineI.h',
				'<(main_project_path)/socialgraph/recommendation_online/home/online/recommendationonlineI.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
			],
			'dependencies' : [
			],
		},
		{
			'target_name' : 'DistributionManager',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/distribution_manager/distribution_managerI.h',
				'<(main_project_path)/socialgraph/recommendation_online/distribution_manager/distribution_managerI.cc',
				'<(main_project_path)/socialgraph/recommendation_online/distribution_manager/selector.h',
				'<(main_project_path)/socialgraph/recommendation_online/distribution_manager/selector.cc',
				'<(main_project_path)/socialgraph/recommendation_online/distribution_manager/create_feed_helper.h',
				'<(main_project_path)/socialgraph/recommendation_online/distribution_manager/create_feed_helper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/distribution_manager/album_util.h',
				'<(main_project_path)/socialgraph/recommendation_online/distribution_manager/album_util.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser2.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser2.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/id_filter.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/id_filter.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/recommendation_helper.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/recommendation_helper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/feed_impl/feed_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/feed_impl/feed_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
        '<(oce_slice_path)/FeedCreator.h',
        '<(oce_slice_path)/FeedCreator.cpp',
        '<(oce_slice_path)/RFeed.h',
        '<(oce_slice_path)/RFeed.cpp',
				'<(oce_slice_path)/DistributionManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',

        #### Cpp Files Generated from ICE ######
        '<(adapter_path)/RecommendationExperimentIAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentIIAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentIIIAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentIVAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentVAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentVIAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentVIIAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentVIIIAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentVIIIIAdapter.cpp',
        '<(adapter_path)/RecommendationExperimentVVAdapter.cpp',
        '<(adapter_path)/RecommendationOnlineAdapter.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
        '<(adapter_path)/SocialGraphRcdPageCfTripodAdapter.cpp',
        '<(adapter_path)/RecommendationFeedOnlineAdapter.cpp',
        '<(adapter_path)/RecommendationFeedExperimentIAdapter.cpp',
        '<(adapter_path)/MonitorAdapter.cpp',

        '<(adapter_path)/SocialGraphCommonTripodAdapter.cpp',
        '<(adapter_path)/FeedCreatorAdapter.h',
        '<(adapter_path)/FeedCreatorAdapter.cpp',
        '<(adapter_path)/UserNameTripodAdapter.h',
        '<(adapter_path)/UserWorkplaceTripodAdapter.cpp',
        '<(adapter_path)/UserUniversityTripodAdapter.cpp',
			],
			'dependencies' : [
				'../user/user_slice_and_adapter.gyp:*',
        '../3rdparty.gyp:hiredis',
        '../base.gyp:base',
        '../xce_base.gyp:xce_base',
        '../tripod2.gyp:tripod_core',
			],
		},
		{
			'target_name' : 'ReloadUtil',
			'type' : 'executable',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/reload/main.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/friend_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/home_impl/commondbhelper.cc',
				
				#### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/DistributionManager.cpp',
				'<(oce_slice_path)/RecommendationManager.cpp',
				'<(oce_slice_path)/Monitor.cpp',

				#### Cpp Files Generated from ICE ######
				'<(adapter_path)/DistributionManagerAdapter.cpp',
				'<(adapter_path)/RecommendationOnlineAdapter.cpp',
				'<(adapter_path)/RecommendationManangerAdapter.cpp',
				'<(adapter_path)/RecommendationExperimentIAdapter.cpp',
				'<(adapter_path)/RecommendationExperimentIIAdapter.cpp',
				'<(adapter_path)/RecommendationExperimentIIIAdapter.cpp',
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
				'<(adapter_path)/MonitorAdapter.cpp',
			],
			'dependencies' : [
			],
		},
  	{
  	  'target_name': 'socialgraph_tpl',
  	  'type': 'none',
  	  'sources': [
  	     '<(main_project_path)/socialgraph/socialgraphd_backup/tpl/ffw.tpl',
  	     '<(main_project_path)/socialgraph/socialgraphd_backup/tpl/ffucr.tpl',
  	     '<(main_project_path)/socialgraph/socialgraphd_backup/tpl/ffwr.tpl',
  	     '<(main_project_path)/socialgraph/socialgraphd_backup/tpl/ffncw.tpl',
  	     '<(main_project_path)/socialgraph/socialgraphd_backup/tpl/rvideo.tpl',
  	     '<(main_project_path)/socialgraph/socialgraphd_backup/tpl/rblog.tpl',
  	  ],
  	  'rules': [
  	     {
  	      'rule_name':'gentpl',
  	      'extension':'tpl',
  	      'inputs': [],
  	      'variables': {
  	         # The protoc compiler requires a proto_path argument with the
  	         # directory containing the .proto file.
  	         # There's no generator variable that corresponds to this, so fake it.
  	        'rule_input_relpath':'<(main_project_path)/socialgraph/socialgraphd_backup/tpl',
  	       },
  	      'outputs': [
  	        '<(rule_input_relpath)/<(RULE_INPUT_ROOT).h',
  	       ],
  	      'action': [
  	        '<(MAKE_TPL_VARNAMES_PATH)',
  	        '--header_dir=<(rule_input_relpath)',
  	        '<(rule_input_relpath)/<(RULE_INPUT_NAME)',
  	       ],
  	      'message':'Generating C++ code from <(RULE_INPUT_PATH)',
  	     },
  	    ],
  	},
	  #{
   	#	'target_name': 'socialgraphd_backup',
   	#	'type': 'executable',
   	#	'include_dirs':[
   	#	#   '../OceProto/proto/',
   	#	#   '../IceExt/src',
   	#	#   '../UtilCxx/src',
   	#	#   '../UtilSlice/slice',
   	#	#   '../OceSlice/slice',
   	#	#   '../DbCxxPool/src',
		# 		'<(main_project_path)/IceExt/src',
    # 		'<(main_project_path)/UtilCxx/src',
    # 		'<(main_project_path)/OceSlice/slice',
    # 		'<(main_project_path)/UtilSlice/slice',
    # 		'<(main_project_path)/OceProto/proto/',
    # 		'<(main_project_path)/DbCxxPool/src',
    # 		'/usr/local/distcache/include/',
   	#	],
   	#	'dependencies':[
		#		 #'../base.gyp:base',
   	#	   'base.gyp:base',
   	#	   'cwf.gyp:cwf',
   	#	   'cwf.gyp:cwfmain',
   	#	   'fcgi.gyp:fcgi',
   	#	   #'dbdesc.gyp:dbpool',
   	#	   'oceadapter.gyp:utiladapter',
   	#	   'oceadapter.gyp:oceadapter',
   	#	   #'socialgraph_util',
   	#	   'socialgraph_tpl',
   	#	],
   	#	'conditions':[
   	#	   ['OS=="linux"', {
   	#	     'libraries': [],
   	#	     'link_settings': {
   	#	       'ldflags': [
   	#	         '-Wl,-rpath <(BOOST_PATH)/lib',
   	#	         '-Wl,-rpath <(ICE_PATH)/lib64',
   	#	         '-Wl,-rpath /usr/local/xce-dev/lib64',
   	#	         '-Wl,-rpath /usr/local/distcache/lib',
   	#	         '-Wl,-rpath /usr/local/xce/lib/',
   	#	       ],
   	#	     },
   	#	  }],
   	#	],
   	#	'sources': [
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/headurl.cc', 
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/base_action.cc', 
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/layout.cc',
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/action.cc',
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/register.cc',
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/base_action.h',
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/socialgraphlogic_adapter.h',
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/headurl.h',
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/layout.h',
   	#	 	'<(main_project_path)/socialgraph/socialgraphd_backup/action.h',

		#		#### Cpp Files Generated from ICE ######
		#		'<(oce_slice_path)/DistributionManager.cpp',
		#		'<(oce_slice_path)/RecommendationManager.cpp',
		#		'<(oce_slice_path)/DistributionManager.cpp',
		#		'<(oce_slice_path)/Monitor.cpp',

    #    #### Cpp Files Generated from ICE ######
		#		'<(adapter_path)/DistributionManagerAdapter.cpp',
    #    '<(adapter_path)/RecommendationExperimentIAdapter.cpp',
    #    '<(adapter_path)/RecommendationExperimentIIAdapter.cpp',
    #    '<(adapter_path)/RecommendationExperimentIIIAdapter.cpp',
    #    '<(adapter_path)/RecommendationExperimentIVAdapter.cpp',
    #    '<(adapter_path)/RecommendationOnlineAdapter.cpp',
    #    '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
    #    '<(adapter_path)/MonitorAdapter.cpp',

    #    #### external dependencies from ICE ######
		#	'<(main_project_path)/arch/site_xiaonei.h',
		#	'<(main_project_path)/arch/site_xiaonei.cc',
		#	'<(main_project_path)/OceSlice/slice/UserCache.h',
		##	'<(main_project_path)/OceSlice/slice/UserCache.h',
		##	'<(main_project_path)/OceSlice/slice/UserCache.cpp',
		##	#'<(main_project_path)/OceSlice/slice/BuddyCore.h',
		##	#'<(main_project_path)/OceSlice/slice/BuddyCore.cpp',
    ##  #'<(main_project_path)/OceSlice/slice/BuddyFriendsCache.h',
    ##  #'<(main_project_path)/OceSlice/slice/BuddyFriendsCache.cpp',
		##	'<(main_project_path)/OceSlice/slice/XceStorm.h',
		##	'<(main_project_path)/OceSlice/slice/XceStorm.cpp',
		##	'<(main_project_path)/OceSlice/slice/UserBase.h',
		##	'<(main_project_path)/OceSlice/slice/UserBase.cpp',
		##	'<(main_project_path)/OceSlice/slice/Ticket.h',
		##	'<(main_project_path)/OceSlice/slice/Ticket.cpp',
		##	'<(main_project_path)/OceSlice/slice/SocialGraphMessage.h',
		##	'<(main_project_path)/OceSlice/slice/SocialGraphMessage.cpp',
		##	'<(main_project_path)/OceSlice/slice/SocialGraphLogic.h',
		##	'<(main_project_path)/OceSlice/slice/SocialGraphLogic.cpp',
		##	'<(main_project_path)/OceSlice/slice/SocialGraphWorker.h',
		##	'<(main_project_path)/OceSlice/slice/SocialGraphWorker.cpp',
		##	'<(main_project_path)/OceSlice/slice/Tips.h',
		##	'<(main_project_path)/OceSlice/slice/Tips.cpp',
		##	'<(main_project_path)/OceSlice/slice/BuddyByIdCache.h',
		##	'<(main_project_path)/OceSlice/slice/BuddyByIdCache.cpp',
		##	'<(main_project_path)/OceSlice/slice/FriendClusterCache.h',
		##	'<(main_project_path)/OceSlice/slice/FriendClusterCache.cpp',
		##	'<(main_project_path)/OceSlice/slice/CardCache.h',
		##	'<(main_project_path)/OceSlice/slice/CardCache.cpp',
		##	'<(main_project_path)/OceSlice/slice/SearchCache.h',
		##	'<(main_project_path)/OceSlice/slice/SearchCache.cpp',
		##	'<(main_project_path)/OceSlice/slice/SearchServer.h',
		##	'<(main_project_path)/OceSlice/slice/SearchServer.cpp',
		##	'<(main_project_path)/OceSlice/slice/SearchModel.h',
		##	'<(main_project_path)/OceSlice/slice/SearchModel.cpp',
		##	'<(main_project_path)/OceSlice/slice/Login.h',
		##	'<(main_project_path)/OceSlice/slice/Login.cpp',
		##	'<(main_project_path)/OceSlice/slice/OzeinContent.h',
		##	'<(main_project_path)/OceSlice/slice/OzeinContent.cpp',
		##	'<(main_project_path)/OceSlice/slice/UserDanger.h',
		##	'<(main_project_path)/OceSlice/slice/UserDanger.cpp',
    ##  '<(main_project_path)/OceSlice/slice/ContentRcd.h',
    ##  '<(main_project_path)/OceSlice/slice/ContentRcd.cpp',
    ##  '<(main_project_path)/OceSlice/slice/SocialGraphRelation.h',
    ##  '<(main_project_path)/OceSlice/slice/SocialGraphRelation.cpp',
    ##  '<(main_project_path)/OceSlice/slice/SocialGraphReport.h',
    ##  '<(main_project_path)/OceSlice/slice/SocialGraphReport.cpp',
    ##  '<(main_project_path)/OceSlice/slice/SocialGraphRcdMessageService.h',
    ##  '<(main_project_path)/OceSlice/slice/SocialGraphRcdMessageService.cpp',
    ##  '<(main_project_path)/OceSlice/slice/RecommendationManager.h',
    ##  '<(main_project_path)/OceSlice/slice/RecommendationManager.cpp',
    ##  '<(main_project_path)/OceSlice/slice/DistributionManager.h',
    ##  '<(main_project_path)/OceSlice/slice/DistributionManager.cpp',
		##	'<(main_project_path)/UtilCxx/src/Singleton.h',
		##	'<(main_project_path)/UtilCxx/src/LogWrapper.h',
		##	'<(main_project_path)/UtilCxx/src/TaskManager.cpp',
		##	'<(main_project_path)/UtilCxx/src/Allocator.cpp',
		##	'<(main_project_path)/UtilCxx/src/CharsetCnvtr.cpp',
		##	'<(main_project_path)/UtilCxx/src/Date.cpp',
		##	'<(main_project_path)/UtilCxx/src/Parser.cpp',
		##	'<(main_project_path)/UtilCxx/src/Pipe.cpp',
		##	'<(main_project_path)/UtilCxx/src/quicklz.cpp',
		##	'<(main_project_path)/UtilCxx/src/ThreadPoolExecutor.cpp',
		##	'<(main_project_path)/UtilCxx/src/ThreadPoolScheduler.cpp',
		##	'<(main_project_path)/IceExt/src/AdapterI.cpp',
		##	'<(main_project_path)/IceExt/src/Channel.cpp',
		##	'<(main_project_path)/IceExt/src/DataSet.h',
		##	'<(main_project_path)/IceExt/src/DataWrapperI.cpp',
		##	'<(main_project_path)/IceExt/src/IceAmdTask.h',
		##	'<(main_project_path)/IceExt/src/IceLogger.h',
		##	'<(main_project_path)/IceExt/src/ObjectCacheI.cpp',
		##	'<(main_project_path)/IceExt/src/ServiceI.cpp',
		##	'<(main_project_path)/IceExt/src/TopicI.cpp',
		##	'<(main_project_path)/IceExt/src/TopicManagerI.cpp',
		##	'<(main_project_path)/IceExt/src/XceStormAdapter.cpp',
    ##  '<(main_project_path)/ReplicaCluster/ClusterState/src/client/cxx/ClusterStateSubscriber.cpp', 
    ##  '<(main_project_path)/ReplicaCluster/SubjectObserver/src/client/cxx/SbjTopicI.cpp',
    ##  '<(main_project_path)/ReplicaCluster/ClusterState/src/client/cxx/ClientInterface.h', 
    ##  '<(main_project_path)/ReplicaCluster/ClusterState/src/client/cxx/ClusterClient.h', 
		##	#'<(main_project_path)/OceCxxAdapter/src/FriendClusterCacheAdapter.h',
		##	#'<(main_project_path)/OceCxxAdapter/src/FriendClusterCacheAdapter.cpp',
		##	#'<(main_project_path)/OceCxxAdapter/src/BuddyByIdReplicaAdapter.h',
		##	#'<(main_project_path)/OceCxxAdapter/src/BuddyByIdReplicaAdapter.cpp',
		##	#'<(main_project_path)/OceCxxAdapter/src/BuddyCoreAdapter.h',
		##	#'<(main_project_path)/OceCxxAdapter/src/BuddyCoreAdapter.cpp',
		##	#'<(main_project_path)/OceCxxAdapter/src/BuddyFriendsAdapter.h',
		##	#'<(main_project_path)/OceCxxAdapter/src/BuddyFriendsAdapter.cpp',
		##	#'<(main_project_path)/OceCxxAdapter/src/CardImportCacheAdapter.h',
		##	#'<(main_project_path)/OceCxxAdapter/src/CardImportCacheAdapter.cpp',
    ##  '<(main_project_path)/OceCxxAdapter/src/LoginLogicAdapter.h',
    ##  '<(main_project_path)/OceCxxAdapter/src/LoginLogicAdapter.cpp',
    ##  '<(main_project_path)/OceCxxAdapter/src/UserDangerAdapter.h',
    ##  '<(main_project_path)/OceCxxAdapter/src/UserDangerAdapter.cpp',
 		##	'<(main_project_path)/OceCxxAdapter/src/TicketAdapter.h',
 		##	'<(main_project_path)/OceCxxAdapter/src/TicketAdapter.cpp',
 		##	'<(main_project_path)/OceCxxAdapter/src/UserBasicAdapter.h',
 		##	'<(main_project_path)/OceCxxAdapter/src/UserBasicAdapter.cpp',
    ##  '<(main_project_path)/OceCxxAdapter/src/UserCacheAdapter.cpp', 
    ##  '<(main_project_path)/OceCxxAdapter/src/DistUserCacheReloaderAdapter.cpp', 
 		##	'<(main_project_path)/OceCxxAdapter/src/TipsAdapter.h',
 		##	'<(main_project_path)/OceCxxAdapter/src/TipsAdapter.cpp',
 		##	'<(main_project_path)/OceCxxAdapter/src/ContentRcdAdapter.h',
 		##	'<(main_project_path)/OceCxxAdapter/src/ContentRcdAdapter.cpp',
 		##	'<(main_project_path)/OceCxxAdapter/src/SocialGraphRelationAdapter.h',
 		##	'<(main_project_path)/OceCxxAdapter/src/SocialGraphRelationAdapter.cpp',
 		##	'<(main_project_path)/OceCxxAdapter/src/SocialGraphReportServiceAdapter.h',
 		##	'<(main_project_path)/OceCxxAdapter/src/SocialGraphReportServiceAdapter.cpp',
 		##	'<(main_project_path)/OceCxxAdapter/src/SocialGraphRcdMessageServiceAdapter.h',
 		##	'<(main_project_path)/OceCxxAdapter/src/SocialGraphRcdMessageServiceAdapter.cpp',
    ##  '<(main_project_path)/OceCxxAdapter/src/XceLoggerReplicaAdapter.h',
    ##  '<(main_project_path)/OceCxxAdapter/src/XceLoggerReplicaAdapter.cpp',
    ##  '<(main_project_path)/OceCxxAdapter/src/ActiveTrackAdapter.h',
    ##  '<(main_project_path)/OceCxxAdapter/src/ActiveTrackAdapter.cpp',   
    ##  '<(main_project_path)/OceCxxAdapter/src/XceLoggerAdapter.h',
    ##  '<(main_project_path)/OceCxxAdapter/src/XceLoggerAdapter.cpp',   
   	#	],
    #},
		{
			'target_name' : 'RecommendationFeedOnline',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/feed/online/recommendation_feed_onlineI.h',
				'<(main_project_path)/socialgraph/recommendation_online/feed/online/recommendation_feed_onlineI.cc',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser2.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser2.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/feed_impl/feed_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/feed_impl/feed_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

        #### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
        '<(oce_slice_path)/FeedCreator.h',
        '<(oce_slice_path)/FeedCreator.cpp',
        '<(oce_slice_path)/RFeed.h',
        '<(oce_slice_path)/RFeed.cpp',

        #### Cpp Files Generated from ICE ######
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
        '<(adapter_path)/SocialGraphCommonTripodAdapter.cpp',
        '<(adapter_path)/FeedCreatorAdapter.h',
        '<(adapter_path)/FeedCreatorAdapter.cpp',
        '<(adapter_path)/UserNameTripodAdapter.h',
        '<(adapter_path)/UserWorkplaceTripodAdapter.cpp',
        '<(adapter_path)/SocialGraphRcdPageCfTripodAdapter.cpp',
        '<(adapter_path)/UserUniversityTripodAdapter.cpp',
			],
			'dependencies' : [
				'../user/user_slice_and_adapter.gyp:*',
        '../3rdparty.gyp:hiredis',
        '../base.gyp:base',
        '../xce_base.gyp:xce_base',
        '../tripod2.gyp:tripod_core',
			],
		},
		{
			'target_name' : 'RecommendationFeedExperimentI',
			'type' : 'shared_library',
			'sources' : [
				'<(main_project_path)/socialgraph/recommendation_online/feed/experimentI/recommendation_feed_experimentI.h',
				'<(main_project_path)/socialgraph/recommendation_online/feed/experimentI/recommendation_feed_experimentI.cc',
	'<(main_project_path)/socialgraph/recommendation_online/common/config_parser2.h',
        '<(main_project_path)/socialgraph/recommendation_online/common/config_parser2.cc',
         			'<(main_project_path)/socialgraph/recommendation_online/builder/feed_impl/feed_recommend_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/feed_impl/feed_recommend_builder.cc',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.h',
				'<(main_project_path)/socialgraph/recommendation_online/builder/base_builder.cc',

        #### Cpp Files Generated from ICE ######
				'<(oce_slice_path)/RecommendationManager.cpp',
        '<(oce_slice_path)/FeedCreator.h',
        '<(oce_slice_path)/FeedCreator.cpp',
        '<(oce_slice_path)/RFeed.h',
        '<(oce_slice_path)/RFeed.cpp',

        #### Cpp Files Generated from ICE ######
        '<(adapter_path)/SocialGraphRcdTripodAdapter.cpp',
        '<(adapter_path)/SocialGraphCommonTripodAdapter.cpp',
        '<(adapter_path)/FeedCreatorAdapter.h',
        '<(adapter_path)/FeedCreatorAdapter.cpp',
        '<(adapter_path)/UserNameTripodAdapter.h',
        '<(adapter_path)/UserWorkplaceTripodAdapter.cpp',
        '<(adapter_path)/SocialGraphRcdPageCfTripodAdapter.cpp',
        '<(adapter_path)/UserUniversityTripodAdapter.cpp',
			],
			'dependencies' : [
				'../user/user_slice_and_adapter.gyp:*',
                                '../3rdparty.gyp:hiredis',
                                '../base.gyp:base',
                                '../xce_base.gyp:xce_base',
                                '../tripod2.gyp:tripod_core',

			],
		},
	  {
      'target_name' : 'GuideRecommendContent',
      'type' : 'shared_library',
      'sources' : [
        '<(main_project_path)/socialgraph/guide_recommend_content/src/guide_recommend_contentI.h',
        '<(main_project_path)/socialgraph/guide_recommend_content/src/guide_recommend_contentI.cc',
        '<(main_project_path)/socialgraph/guide_recommend_content/src/commondbhelper.h',
        '<(main_project_path)/socialgraph/guide_recommend_content/src/commondbhelper.cc',
        '<(main_project_path)/socialgraph/guide_recommend_content/src/create_feed_helper.h',
        '<(main_project_path)/socialgraph/guide_recommend_content/src/create_feed_helper.cc',
        '<(main_project_path)/socialgraph/guide_recommend_content/src/album_util.h',
        '<(main_project_path)/socialgraph/guide_recommend_content/src/album_util.cc',

        #### Cpp Files Generated from ICE ######
        '<(oce_slice_path)/GuideRecommendContent.cpp',
        '<(oce_slice_path)/Monitor.cpp',
        '<(oce_slice_path)/FeedCreator.h',
        '<(oce_slice_path)/FeedCreator.cpp',
        '<(oce_slice_path)/RFeed.h',
        '<(oce_slice_path)/RFeed.cpp',

        #### Cpp Files Generated from ICE ######
        '<(adapter_path)/FeedCreatorAdapter.h',
        '<(adapter_path)/FeedCreatorAdapter.cpp',
        '<(adapter_path)/MonitorAdapter.cpp',
        '<(adapter_path)/SocialGraphCommonTripodAdapter.cpp',
        '<(adapter_path)/UserNameTripodAdapter.h',
        '<(adapter_path)/UserWorkplaceTripodAdapter.cpp',
        '<(adapter_path)/UserUniversityTripodAdapter.cpp',

      ],
      'dependencies' : [
        '../user/user_slice_and_adapter.gyp:*',
      ],
   },
	]
}
