<%@ page pageEncoding="UTF-8" %>
<%-- make Struts XHTML-compliant --%>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="${applicationScope.urlSmallStatic}/css/im/im.css?ver=$revxxx$" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/util.js?ver=$revxxx$"></script>
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/jspro/base.js?ver=$revxxx$"></script>ss
<script type="text/javascript" src="${applicationScope.urlSmallStatic}/js/prototype.js?ver=$revxxx$"></script>
