<%@ page contentType="text/html;charset=UTF-8" session="false" %>
<section data-type="high">
	<dl class="f-s">
		<dt><label for="">高中：</label></dt>
		<dd>
			<input class="inputtext s-select s-high" data-type="name" data-tip="xxx" />
		</dd>
	</dl>
	<dl>
		<dt><label for="">入学年份：</label></dt>
		<dd>
			<select class="y-comp" data-type="year" data-tip="xxx"><option>--</option></select>
		</dd>
	</dl>
	<dl>
		<dt><label for="">班级：</label></dt>
		<dd>
			高一 <input type="text" class="inputtext small" />
			高二 <input type="text" class="inputtext small" />
			高三 <input type="text" class="inputtext small" data-tip="xxx" />
		</dd>
	</dl>
</section>